In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string
import nltk

In [2]:
df = pd.read_csv(r"C:\Users\TOSHIBA\Documents\Github\FateAi\DATAS\divorces_2000-2015_man.csv")

In [3]:
#show full text of columns
pd.set_option('display.max_colwidth', -1)
#show all columns
pd.set_option('display.max_columns', None)
#show 3 rows only
# pd.set_option('display.max_rows', 5)
# show 10 rows only
pd.set_option('display.max_rows', 10)

C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_16116\3836281045.py:2: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)

In [4]:
#get only Divorce_date,Date_of_marriage,Marriage_duration,Type_of_divorce,Num_Children,DOB_partner_man,Level_of_education_partner_man,DOB_partner_woman,Level_of_education_partner_woman

new_df = df[['uniqueid','Divorce_date', 'Date_of_marriage', 'Age_partner_man','Marriage_duration', 'Type_of_divorce', 'Num_Children', 'DOB_partner_man', 'Level_of_education_partner_man']]
# new_df

In [5]:
import pandas as pd


# convert the date string to a datetime object
new_df['DOB_partner_man'] = pd.to_datetime(new_df['DOB_partner_man'], format='%d/%m/%y')

# subtract the year by 2000 and add 1900 only if the year>2000
new_df['DOB_partner_man'] = new_df['DOB_partner_man'].apply(lambda x: x.replace(year=x.year-2000+1900) if x.year>2000 else x)

new_df
# convert the date string to a datetime object
new_df['Date_of_marriage'] = pd.to_datetime(new_df['Date_of_marriage'], format='%d/%m/%y')

# subtract the year by 2000 and add 1900 only if the year>2000
new_df['Date_of_marriage'] = new_df['Date_of_marriage'].apply(lambda x: x.replace(year=x.year-2000+1900) if x.year>2023 else x)
# convert the date string to a datetime object
new_df['Divorce_date'] = pd.to_datetime(new_df['Divorce_date'], format='%d/%m/%y')

# subtract the year by 2000 and add 1900 only if the year>2000
new_df['Divorce_date'] = new_df['Divorce_date'].apply(lambda x: x.replace(year=x.year-2000+1900) if x.year>2015 else x)
#get year of Date_of_marriage
new_df['year_of_marriage'] = new_df['Date_of_marriage'].dt.year
#
new_df['year_of_DOB'] = new_df['DOB_partner_man'].dt.year

new_df['year_of_Divorse'] = new_df['Divorce_date'].dt.year
new_df['month_of_DOB'] = new_df['DOB_partner_man'].dt.month
new_df['day_of_DOB'] = new_df['DOB_partner_man'].dt.day

C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_16116\4000869105.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['DOB_partner_man'] = pd.to_datetime(new_df['DOB_partner_man'], format='%d/%m/%y')
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_16116\4000869105.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['DOB_partner_man'] = new_df['DOB_partner_man'].apply(lambda x: x.replace(year=x.year-2000+1900) if x.year>2000 else x)
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_16116\4000869105.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Date_of_marriage'] = pd.to_datetime(new_df['Date_of_marriage'], format='%d/%m/%y')
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_16116\4000869105.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Date_of_marriage'] = new_df['Date_of_marriage'].apply(lambda x: x.replace(year=x.year-2000+1900) if x.year>2023 else x)
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_16116\4000869105.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Divorce_date'] = pd.to_datetime(new_df['Divorce_date'], format='%d/%m/%y')
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_16116\4000869105.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Divorce_date'] = new_df['Divorce_date'].apply(lambda x: x.replace(year=x.year-2000+1900) if x.year>2015 else x)
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_16116\4000869105.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['year_of_marriage'] = new_df['Date_of_marriage'].dt.year
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_16116\4000869105.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['year_of_DOB'] = new_df['DOB_partner_man'].dt.year
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_16116\4000869105.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['year_of_Divorse'] = new_df['Divorce_date'].dt.year
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_16116\4000869105.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['month_of_DOB'] = new_df['DOB_partner_man'].dt.month
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_16116\4000869105.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['day_of_DOB'] = new_df['DOB_partner_man'].dt.day

In [6]:
#show rows where year_of_marriage is less than year_of_DOB
new_df[new_df['year_of_marriage'] < new_df['year_of_DOB']]

,uniqueid,Divorce_date,Date_of_marriage,Age_partner_man,Marriage_duration,Type_of_divorce,Num_Children,DOB_partner_man,Level_of_education_partner_man,year_of_marriage,year_of_DOB,year_of_Divorse,month_of_DOB,day_of_DOB
427,427,2001-01-04,1931-08-31,57.0,30.0,Voluntario,4.0,1943-06-03,PREPARATORIA,1931,1943,2001,6,3

In [7]:
# for index equal 462, change the year_of_marriage to Divorce_date - Marriage_duration
new_df.loc[427, 'year_of_marriage'] = new_df.loc[427, 'Divorce_date'].year - new_df.loc[427, 'Marriage_duration']

In [8]:
#show rows where year_of_marriage is less than year_of_DOB
new_df[new_df['year_of_marriage'] < new_df['year_of_DOB']]

Empty DataFrame
Columns: [uniqueid, Divorce_date, Date_of_marriage, Age_partner_man, Marriage_duration, Type_of_divorce, Num_Children, DOB_partner_man, Level_of_education_partner_man, year_of_marriage, year_of_DOB, year_of_Divorse, month_of_DOB, day_of_DOB]
Index: []

In [9]:
new_df[new_df['year_of_marriage'] > new_df['year_of_Divorse']]

Empty DataFrame
Columns: [uniqueid, Divorce_date, Date_of_marriage, Age_partner_man, Marriage_duration, Type_of_divorce, Num_Children, DOB_partner_man, Level_of_education_partner_man, year_of_marriage, year_of_DOB, year_of_Divorse, month_of_DOB, day_of_DOB]
Index: []

In [10]:
new_df

,uniqueid,Divorce_date,Date_of_marriage,Age_partner_man,Marriage_duration,Type_of_divorce,Num_Children,DOB_partner_man,Level_of_education_partner_man,year_of_marriage,year_of_DOB,year_of_Divorse,month_of_DOB,day_of_DOB
0,0,2006-06-09,2000-06-26,30.0,5.0,Necesario,1.0,1975-12-18,SECUNDARIA,2000,1975,2006,12,18
1,1,2005-02-01,1975-12-18,49.0,NaN,Necesario,NaN,1955-02-22,PREPARATORIA,1975,1955,2005,2,22
2,2,2006-02-01,1987-12-03,42.0,18.0,Necesario,2.0,1964-01-20,PROFESIONAL,1987,1964,2006,1,20
3,3,2006-02-01,1998-11-14,30.0,7.0,Necesario,2.0,1975-10-30,PROFESIONAL,1998,1975,2006,10,30
4,4,2006-02-01,1995-01-20,32.0,11.0,Necesario,2.0,1973-03-28,SECUNDARIA,1995,1973,2006,3,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4537,4537,2012-10-31,2008-10-25,35.0,3.0,Voluntario,NaN,1977-10-29,PROFESIONAL,2008,1977,2012,10,29
4538,4538,2013-10-31,2012-05-26,30.0,1.0,Voluntario,NaN,1982-11-10,PROFESIONAL,2012,1982,2013,11,10
4539,4539,2013-10-31,1978-06-02,59.0,35.0,Voluntario,2.0,1954-10-28,PROFESIONAL,1978,1954,2013,10,28
4540,4540,2012-12-31,1979-11-05,54.0,33.0,Voluntario,2.0,1958-02-07,PREPARATORIA,1979,1958,2012,2,7
4541,4541,2013-12-31,2009-08-22,53.0,4.0,Voluntario,NaN,1960-06-22,PROFESIONAL,2009,1960,2013,6,22

In [24]:
from selenium import webdriver
import time
from selenium.webdriver.support.ui import Select
driver = webdriver.Chrome()
import pandas as pd
from selenium.webdriver.common.by import By

def getDayun(year,month,day,year_of_marriage,index):
    
    year=str(year)
    month=str(month)
    day=str(day)
    hr="0"
    gender="Male"

    driver.get("https://fatew.com/")
    select = Select(driver.find_element(By.NAME, "hityear"))
    select.select_by_value(year)

    select = Select(driver.find_element(By.NAME, "hitmonth"))
    select.select_by_visible_text(month)

    select = Select(driver.find_element(By.NAME, "hitday"))
    select.select_by_visible_text(day)

    select = Select(driver.find_element(By.NAME, "hittime"))
    # select.select_by_value(hr)
    select.select_by_visible_text(hr)

    if gender == "Male":
        driver.find_elements(By.ID,'male')[0].click()
        #click on the radio button by class="myradio"
        # driver.find_element_by_css_selector("input[type='radio'][value='1']").click()
        # modify he above line to make it work, there s AttributeError: 'WebDriver' object has no attribute 'find_element_by_css_selector'
        

    if gender =="Female":
        driver.find_elements(By.ID,'female')[0].click()

    driver.find_elements(By.CSS_SELECTOR,"input[type='submit'][id='submitb']")[0].click()

    returnv=driver.find_elements(By.XPATH,"//font[@size = '6' and @face='標楷體']")

    baz=""
    for i in returnv:
        baz=baz+i.text

    baz=baz.replace("\n", "")
    b=baz[0:4]+baz[5:]
    bazi=list(b.strip())
    print(bazi)



    table_element = driver.find_elements(By.XPATH,'//table[@border="1" and @cellspacing="0" and @cellpadding="0" and @bordercolor="#F2F2F2"]')

    # Convert the table element into a string of HTML
    table_html = table_element[0].get_attribute('outerHTML')

    # Use Pandas to parse the HTML string into a DataFrame
    df = pd.read_html(table_html)[0]

    #make first row as header
    new_header = df.iloc[0] #grab the first row for the header
    df = df[1:] #take the data less the header row
    df.columns = new_header #set the header row as the df header
    #rename df to dayunliunian
    dayunliunian=df
    #save to csv
    dayunliunian.to_csv(f"{index}dayun.csv",index=False)
    # if year_of_marriage == 西元 in dayunliunian: get the carrasponding 大運 at that year
    dayun=dayunliunian[dayunliunian['西元'] == str(year_of_marriage)]['大運'].values[0]

    return dayun

In [11]:
#dreate a new column called DONE and set it to 0
new_df['DONE'] = 0
#create a new column called dayun and set it to None
new_df['dayun'] = None

C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_16116\936742560.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['DONE'] = 0

In [25]:
for index, row in new_df.iterrows():
    #if DONE is 0, then do the following
    if row['DONE'] == 0:
        try:
            year=str(row['year_of_DOB'])
            month=str(row['month_of_DOB'])
            day=str(row['day_of_DOB'])
            hr="0"
            gender="Male"
            year_of_marriage=row['year_of_marriage']

            driver.get("https://fatew.com/")
            select = Select(driver.find_element(By.NAME, "hityear"))
            select.select_by_value(year)

            select = Select(driver.find_element(By.NAME, "hitmonth"))
            select.select_by_visible_text(month)

            select = Select(driver.find_element(By.NAME, "hitday"))
            select.select_by_visible_text(day)

            select = Select(driver.find_element(By.NAME, "hittime"))
            # select.select_by_value(hr)
            select.select_by_visible_text(hr)

            if gender == "Male":
                driver.find_elements(By.ID,'male')[0].click()
                #click on the radio button by class="myradio"
                # driver.find_element_by_css_selector("input[type='radio'][value='1']").click()
                # modify he above line to make it work, there s AttributeError: 'WebDriver' object has no attribute 'find_element_by_css_selector'
                

            if gender =="Female":
                driver.find_elements(By.ID,'female')[0].click()

            driver.find_elements(By.CSS_SELECTOR,"input[type='submit'][id='submitb']")[0].click()

            returnv=driver.find_elements(By.XPATH,"//font[@size = '6' and @face='標楷體']")

            baz=""
            for i in returnv:
                baz=baz+i.text

            baz=baz.replace("\n", "")
            b=baz[0:4]+baz[5:]
            # bazi=list(b.strip())
            bazi=b
            # print(bazi)

            #add bazi to new_df
            new_df.loc[index,'bazi']=bazi


            table_element = driver.find_elements(By.XPATH,'//table[@border="1" and @cellspacing="0" and @cellpadding="0" and @bordercolor="#F2F2F2"]')

            # Convert the table element into a string of HTML
            table_html = table_element[0].get_attribute('outerHTML')

            # Use Pandas to parse the HTML string into a DataFrame
            df = pd.read_html(table_html)[0]

            #make first row as header
            new_header = df.iloc[0] #grab the first row for the header
            df = df[1:] #take the data less the header row
            df.columns = new_header #set the header row as the df header
            #rename df to dayunliunian
            dayunliunian=df

            #add bazi to dayunliunian
            dayunliunian['bazi']=bazi
            
            # add uniqueid to dayunliunian
            dayunliunian['uniqueid']=row['uniqueid']
            #save to csv
            dayunliunian.to_csv(f"{row['uniqueid']}fulldayun.csv",index=False)
            # if year_of_marriage == 西元 in dayunliunian: get the carrasponding 大運 at that year
            dayun=dayunliunian[dayunliunian['西元'] == str(year_of_marriage)]['大運'].values[0]

            #add dayun to new_df
            new_df.loc[index,'dayun']=dayun


            #create a new col named DONE
            new_df.loc[index,'DONE']=1

        except:
            new_df.loc[index,'DONE']=0
            #print year month day uniqueid
            print(year,month,day,row['uniqueid'])


            continue

1920 7 8 848
1923 4 7 2988
1922 11 30 4515

In [ ]:
#save new_df to csv file named man_full_dayun.csv
new_df.to_csv('man_full_dayun.csv', index=False)

In [26]:
new_df.head(10)

,uniqueid,Divorce_date,Date_of_marriage,Age_partner_man,Marriage_duration,Type_of_divorce,Num_Children,DOB_partner_man,Level_of_education_partner_man,year_of_marriage,year_of_DOB,year_of_Divorse,month_of_DOB,day_of_DOB,DONE,bazi,dayun
0,0,2006-06-09,2000-06-26,30.0,5.0,Necesario,1.0,1975-12-18,SECUNDARIA,2000,1975,2006,12,18,1,壬子戊戌戊子乙卯,乙酉
1,1,2005-02-01,1975-12-18,49.0,NaN,Necesario,NaN,1955-02-22,PREPARATORIA,1975,1955,2005,2,22,1,甲子甲寅戊寅乙未,丙子
2,2,2006-02-01,1987-12-03,42.0,18.0,Necesario,2.0,1964-01-20,PROFESIONAL,1987,1964,2006,1,20,1,壬子戊辰乙丑癸卯,癸亥
3,3,2006-02-01,1998-11-14,30.0,7.0,Necesario,2.0,1975-10-30,PROFESIONAL,1998,1975,2006,10,30,1,甲子己酉丙戌乙卯,甲申
4,4,2006-02-01,1995-01-20,32.0,11.0,Necesario,2.0,1973-03-28,SECUNDARIA,1995,1973,2006,3,28,1,壬子癸亥乙卯癸丑,癸丑
5,5,2007-02-01,1991-08-16,36.0,15.0,Necesario,2.0,1970-12-13,PROFESIONAL,1991,1970,2007,12,13,1,庚子丁卯戊子庚戌,庚寅
6,6,2007-02-01,1999-09-17,31.0,6.0,Necesario,1.0,1975-02-17,PROFESIONAL,1999,1975,2007,2,17,1,甲子甲午戊寅乙卯,乙亥
7,7,2008-02-01,2006-06-03,31.0,1.0,Voluntario,NaN,1976-12-02,PROFESIONAL,2006,1976,2008,12,2,1,壬子戊子己亥丙辰,壬寅
8,8,2008-02-01,2001-02-09,31.0,7.0,Voluntario,NaN,1976-11-17,PROFESIONAL,2001,1976,2008,11,17,1,壬子癸酉己亥丙辰,辛丑
9,9,2011-02-01,2000-02-02,41.0,2.0,Necesario,2.0,1969-06-04,PREPARATORIA,2000,1969,2011,6,4,1,丙子庚戌己巳己酉,丙寅