In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string
import nltk

from functions import *

In [2]:
#show full text of columns
pd.set_option('display.max_colwidth', -1)
#show all columns
pd.set_option('display.max_columns', None)
#show 3 rows only
# pd.set_option('display.max_rows', 5)
# show 10 rows only
pd.set_option('display.max_rows', 10)

C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\3836281045.py:2: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)

In [3]:
#import man_full_dayun.csv
man_df = pd.read_excel(r"C:\Users\TOSHIBA\Documents\Github\FateAi\Bazi Data Scraping and Analysis\CelebrityCouples.xlsx", header=1)

In [4]:
man_df

,Female name,Female birthday,Male name,Male birthday,Year started relationship,Year broke up
0,Blake Lively,02-25-1987,Ryan Reynolds,02-23-1976,2011,Present
1,Scarlett Johansson,11-22-1984,Colin Jost,06-20-1982,2017,Present
2,Priyanka Chopra,06-18-1982,Nick Jonas,09-16-1992,2018,Present
3,Meghan Markle,1981-04-08 00:00:00,Prince Harry,09-15-1984,2016,Present
4,Amal Clooney,03-16-1978,George Clooney,1961-06-05 00:00:00,2014,Present
...,...,...,...,...,...,...
305,Florence Pugh,1996-01-03 00:00:00,Zach Braff,1975-08-06 00:00:00,2019,Present
306,Hailee Steinfeld,1996-12-11 00:00:00,Niall Horan,1993-09-13 00:00:00,2017,2018
307,Saoirse Ronan,1994-04-12 00:00:00,Jack Lowden,1992-02-01 00:00:00,2018,Present
308,Elle Fanning,1998-04-09 00:00:00,Max Minghella,1985-01-01 00:00:00,2018,Present
309,Chlo毛 Grace Moretz,1997-01-10 00:00:00,Brooklyn Beckham,1999-03-04 00:00:00,2019,Present

In [5]:
#rename columns template
man_df = man_df.rename(columns={'Female birthday': 'female_birthdate', 'Male birthday': 'male_birthdate'})

In [6]:
#conver female birthdate to datetime and male birthdate to datetime
import pandas as pd

# Assuming "female birthdate" column name is "female_birthdate" and "male birthdate" column name is "male_birthdate"
man_df['female_birthdate'] = pd.to_datetime(man_df['female_birthdate'], errors='coerce')
man_df['male_birthdate'] = pd.to_datetime(man_df['male_birthdate'], errors='coerce')

In [7]:
#drop duplicates
man_df.drop_duplicates(inplace=True)
man_df

,Female name,female_birthdate,Male name,male_birthdate,Year started relationship,Year broke up
0,Blake Lively,1987-02-25,Ryan Reynolds,1976-02-23,2011,Present
1,Scarlett Johansson,1984-11-22,Colin Jost,1982-06-20,2017,Present
2,Priyanka Chopra,1982-06-18,Nick Jonas,1992-09-16,2018,Present
3,Meghan Markle,1981-04-08,Prince Harry,1984-09-15,2016,Present
4,Amal Clooney,1978-03-16,George Clooney,1961-06-05,2014,Present
...,...,...,...,...,...,...
287,Marlene Dietrich,1901-12-27,Rudolf Sieber,1890-09-12,1923,1937
288,Joan Crawford,1904-03-23,Franchot Tone,1903-05-27,1935,1939
289,Jennifer Lawrence,1990-08-15,Cooke Maroney,1984-06-04,2018,Present
299,Chlo毛 Grace Moretz,1997-01-10,Brooklyn Beckham,1999-03-04,2019,Present
301,Timoth茅e Chalamet,1995-12-27,Lily-Rose Depp,1999-05-27,2018,2020

In [143]:
#sort by Female name
man_df.sort_values(by='Female name', inplace=True)
man_df

,Female name,female_birthdate,Male name,male_birthdate,Year started relationship,Year broke up
109,Ahn Jae Hyun,1987-01-07,Goo Hye Sun,1984-09-11,2016,2019
226,Alison Brie,1982-12-29,Dave Franco,1985-06-12,2011,Present
4,Amal Clooney,1978-03-16,George Clooney,1961-06-05,2014,Present
114,Amanda Seyfried,1985-12-03,Thomas Sadoski,1976-07-01,2016,Present
151,Amandla Stenberg,1998-10-23,Nick Robinson,1995-11-02,2015,2016
...,...,...,...,...,...,...
141,Zendaya,1996-09-01,Tom Holland,1996-06-01,2021,Present
66,Zhang Ziyi,1979-09-09,Wang Feng,1971-04-03,2015,Present
68,Zhao Wei,1976-12-01,Huang Youming,1976-08-17,2005,Present
75,Zhou Xun,1976-10-01,Gao Yunxiang,1974-07-16,2014,2019
236,Zoe Saldana,1978-06-19,Marco Perego,1979-06-01,2013,Present

In [8]:
selected_columns = ['Male name', 'male_birthdate', 'Year started relationship', 'Year broke up']
man_df = man_df[selected_columns]

In [9]:
man_df

            Male name male_birthdate  Year started relationship Year broke up
0    Ryan Reynolds    1976-02-23      2011                       Present
1    Colin Jost       1982-06-20      2017                       Present
2    Nick Jonas       1992-09-16      2018                       Present
3    Prince Harry     1984-09-15      2016                       Present
4    George Clooney   1961-06-05      2014                       Present
..              ...          ...       ...                           ...
287  Rudolf Sieber    1890-09-12      1923                       1937
288  Franchot Tone    1903-05-27      1935                       1939
289  Cooke Maroney    1984-06-04      2018                       Present
299  Brooklyn Beckham 1999-03-04      2019                       Present
301  Lily-Rose Depp   1999-05-27      2018                       2020

[231 rows x 4 columns]

In [10]:
#save to CelebrityCouples.xlsx

In [11]:
import pandas as pd

# # Original DataFrame
# data = {
#     'Male name': ['Goo Hye Sun', 'Dave Franco', 'George Clooney'],
#     'male_birthdate': ['1984-09-11', '1985-06-12', '1961-06-05'],
#     'Year started relationship': [2016, 2011, 2014],
#     'Year broke up': [2019, 'Present', 'Present']
# }

# man_df = pd.DataFrame(data)

# Convert 'Year started relationship' and 'Year broke up' columns to string type
man_df['Year started relationship'] = man_df['Year started relationship'].astype(str)
man_df['Year broke up'] = man_df['Year broke up'].astype(str)

# Create a new DataFrame to store the transformed data
transformed_man_df = pd.DataFrame(columns=['Male_name', 'male_birthdate', 'Year', 'Event'])

# Iterate over each row in the original DataFrame
for _, row in man_df.iterrows():
    male_name = row['Male name']
    male_birthdate = row['male_birthdate']
    year_started_relationship = row['Year started relationship']
    year_broke_up = row['Year broke up']
    
    # If 'Year broke up' is 'Present', set it to NaN
    if year_broke_up == 'Present':
        year_broke_up = None
    
    # Create rows for 'Year started relationship' and 'Year broke up'
    if pd.notnull(year_started_relationship):
        transformed_man_df = transformed_man_df.append({
            'Male_name': male_name,
            'male_birthdate': male_birthdate,
            'Year': int(year_started_relationship),
            'Event': 1
        }, ignore_index=True)
        
    if pd.notnull(year_broke_up):
        transformed_man_df = transformed_man_df.append({
            'Male_name': male_name,
            'male_birthdate': male_birthdate,
            'Year': int(year_broke_up),
            'Event': 0
        }, ignore_index=True)

# Print the transformed DataFrame
transformed_man_df

C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  man_df['Year started relationship'] = man_df['Year started relationship'].astype(str)
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  man_df['Year broke up'] = man_df['Year broke up'].astype(str)
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:33: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({
C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_14208\381361174.py:41: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transformed_man_df = transformed_man_df.append({

            Male_name male_birthdate  Year Event
0    Ryan Reynolds    1976-02-23      2011  1
1    Colin Jost       1982-06-20      2017  1
2    Nick Jonas       1992-09-16      2018  1
3    Prince Harry     1984-09-15      2016  1
4    George Clooney   1961-06-05      2014  1
..              ...          ...       ... ..
321  Franchot Tone    1903-05-27      1939  0
322  Cooke Maroney    1984-06-04      2018  1
323  Brooklyn Beckham 1999-03-04      2019  1
324  Lily-Rose Depp   1999-05-27      2018  1
325  Lily-Rose Depp   1999-05-27      2020  0

[326 rows x 4 columns]

In [12]:
man_df=transformed_man_df

In [13]:
import sys
sys.path.append(r"C:\Users\TOSHIBA\Documents\Github\FateAi\crystal-bazi")
# import main
import metaphysic
def getBazi(year,month,day,hour):
    ba=metaphysic.bazi(year,month,day,hour)
    ba=ba.split("-")
    bazi=[]
    for i in ba:
        # print(i.split())
        bazi.append(i[0])
        bazi.append(i[1])
    return bazi
bazi=getBazi(1996,9,17,3)
bazi

changed sth
输入:[1996-9-17]; 输出:[1996-8-5]; 天干地支:[丙子-丁酉-丁巳]; 生肖:[鼠]

['丙', '子', '丁', '酉', '丁', '巳', '壬', '寅']

In [14]:
man_df['bazi_man'] = man_df['male_birthdate'].apply(lambda x: None if pd.isnull(x) else None)
for index, row in man_df.iterrows():
    try:
        man_df.at[index, 'bazi_man'] = getBazi(row['male_birthdate'].year, row['male_birthdate'].month, row['male_birthdate'].day, 0)
    except:
        continue

changed sth
输入:[1976-2-23]; 输出:[1976-1-24]; 天干地支:[丙辰-庚寅-乙巳]; 生肖:[龍]
changed sth
输入:[1982-6-20]; 输出:[1982-4-29]; 天干地支:[壬戌-丙午-甲戌]; 生肖:[狗]
changed sth
输入:[1992-9-16]; 输出:[1992-8-20]; 天干地支:[壬申-己酉-乙未]; 生肖:[猴]
changed sth
输入:[1984-9-15]; 输出:[1984-8-20]; 天干地支:[甲子-癸酉-壬子]; 生肖:[鼠]
changed sth
输入:[1961-6-5]; 输出:[1961-4-22]; 天干地支:[辛丑-癸巳-己巳]; 生肖:[牛]
changed sth
输入:[1969-4-12]; 输出:[1969-2-26]; 天干地支:[己酉-戊辰-丁巳]; 生肖:[雞]
changed sth
输入:[1978-12-28]; 输出:[1978-11-29]; 天干地支:[戊午-甲子-甲子]; 生肖:[馬]
changed sth
输入:[1981-1-31]; 输出:[1980-12-26]; 天干地支:[庚申-己丑-己酉]; 生肖:[猴]
changed sth
输入:[1980-12-10]; 输出:[1980-11-4]; 天干地支:[庚申-戊子-丁巳]; 生肖:[猴]
changed sth
输入:[1988-1-28]; 输出:[1987-12-10]; 天干地支:[丁卯-癸丑-壬午]; 生肖:[兔]
changed sth
输入:[1981-2-10]; 输出:[1981-1-6]; 天干地支:[辛酉-庚寅-己未]; 生肖:[雞]
changed sth
输入:[1975-1-9]; 输出:[1974-11-27]; 天干地支:[甲寅-丁丑-乙卯]; 生肖:[虎]
changed sth
输入:[1975-1-9]; 输出:[1974-11-27]; 天干地支:[甲寅-丁丑-乙卯]; 生肖:[虎]
changed sth
输入:[1985-4-6]; 输出:[1985-2-17]; 天干地支:[乙丑-庚辰-乙亥]; 生肖:[牛]
changed sth
输入:[1977-2-4]; 输出:[1977-12-17]; 天干地支:[丁巳-壬寅-壬辰]; 生肖:[蛇]
changed sth
输入:[1996-1-6]; 输出:[1995-11-16]; 天干地支:[乙亥-己丑-壬寅]; 生肖:[豬]
changed sth
输入:[1988-3-3]; 输出:[1988-1-16]; 天干地支:[戊辰-甲寅-丁巳]; 生肖:[龍]
changed sth
输入:[1991-2-15]; 输出:[1991-1-1]; 天干地支:[辛未-庚寅-丙辰]; 生肖:[羊]
changed sth
输入:[1993-12-1]; 输出:[1993-10-18]; 天干地支:[癸酉-癸亥-丙辰]; 生肖:[雞]
changed sth
输入:[1993-12-1]; 输出:[1993-10-18]; 天干地支:[癸酉-癸亥-丙辰]; 生肖:[雞]
changed sth
输入:[1996-3-4]; 输出:[1996-1-15]; 天干地支:[丙子-庚寅-庚子]; 生肖:[鼠]
changed sth
输入:[1990-1-16]; 输出:[1989-12-20]; 天干地支:[己巳-丁丑-辛巳]; 生肖:[蛇]
changed sth
输入:[1990-1-16]; 输出:[1989-12-20]; 天干地支:[己巳-丁丑-辛巳]; 生肖:[蛇]
changed sth
输入:[1978-8-28]; 输出:[1978-7-25]; 天干地支:[戊午-庚申-壬戌]; 生肖:[馬]
changed sth
输入:[1969-4-12]; 输出:[1969-2-26]; 天干地支:[己酉-戊辰-丁巳]; 生肖:[雞]
changed sth
输入:[1960-10-3]; 输出:[1960-8-13]; 天干地支:[庚子-乙酉-甲子]; 生肖:[鼠]
changed sth
输入:[1972-8-15]; 输出:[1972-7-7]; 天干地支:[壬子-戊申-戊寅]; 生肖:[鼠]
changed sth
输入:[1966-12-12]; 输出:[1966-11-1]; 天干地支:[丙午-庚子-乙巳]; 生肖:[馬]
changed sth
输入:[1966-12-12]; 输出:[1966-11-1]; 天干地支:[丙午-庚子-乙巳]; 生肖:[馬]
changed sth
输入:[1967-10-26]; 输出:[1967-9-23]; 天干地支:[丁未-庚戌-癸亥]; 生肖:[羊]
changed sth
输入:[1960-8-17]; 输出:[1960-6-25]; 天干地支:[庚子-甲申-丁丑]; 生肖:[鼠]
changed sth
输入:[1960-8-17]; 输出:[1960-6-25]; 天干地支:[庚子-甲申-丁丑]; 生肖:[鼠]
changed sth
输入:[1970-6-8]; 输出:[1970-5-5]; 天干地支:[庚戌-壬午-己未]; 生肖:[狗]
changed sth
输入:[1970-6-8]; 输出:[1970-5-5]; 天干地支:[庚戌-壬午-己未]; 生肖:[狗]
changed sth
输入:[1977-3-25]; 输出:[1977-2-6]; 天干地支:[丁巳-癸卯-辛巳]; 生肖:[蛇]
changed sth
输入:[1977-3-25]; 输出:[1977-2-6]; 天干地支:[丁巳-癸卯-辛巳]; 生肖:[蛇]
changed sth
输入:[1979-11-3]; 输出:[1979-9-14]; 天干地支:[己未-甲戌-甲戌]; 生肖:[羊]
changed sth
输入:[1978-3-9]; 输出:[1978-2-1]; 天干地支:[戊午-乙卯-庚午]; 生肖:[馬]
changed sth
输入:[1978-3-9]; 输出:[1978-2-1]; 天干地支:[戊午-乙卯-庚午]; 生肖:[馬]
changed sth
输入:[1980-10-9]; 输出:[1980-9-1]; 天干地支:[庚申-丙戌-乙卯]; 生肖:[猴]
changed sth
输入:[1967-1-13]; 输出:[1966-12-3]; 天干地支:[丙午-辛丑-丁丑]; 生肖:[馬]
changed sth
输入:[1979-10-1]; 输出:[1979-8-11]; 天干地支:[己未-癸酉-辛丑]; 生肖:[羊]
changed sth
输入:[1968-2-1]; 输出:[1967-1-3]; 天干地支:[丁未-癸丑-辛丑]; 生肖:[羊]
changed sth
输入:[1971-4-3]; 输出:[1971-3-8]; 天干地支:[辛亥-辛卯-戊午]; 生肖:[豬]
changed sth
输入:[1978-2-10]; 输出:[1978-1-4]; 天干地支:[戊午-甲寅-癸卯]; 生肖:[馬]
changed sth
输入:[1978-2-10]; 输出:[1978-1-4]; 天干地支:[戊午-甲寅-癸卯]; 生肖:[馬]
changed sth
输入:[1976-8-17]; 输出:[1976-7-22]; 天干地支:[丙辰-丙申-辛丑]; 生肖:[龍]
changed sth
输入:[1974-9-9]; 输出:[1974-7-23]; 天干地支:[甲寅-癸酉-癸丑]; 生肖:[虎]
changed sth
输入:[1974-9-9]; 输出:[1974-7-23]; 天干地支:[甲寅-癸酉-癸丑]; 生肖:[虎]
changed sth
输入:[1977-11-17]; 输出:[1977-10-7]; 天干地支:[丁巳-辛亥-戊寅]; 生肖:[蛇]
changed sth
输入:[1977-11-17]; 输出:[1977-10-7]; 天干地支:[丁巳-辛亥-戊寅]; 生肖:[蛇]
changed sth
输入:[1985-10-11]; 输出:[1985-8-27]; 天干地支:[乙丑-丙戌-癸未]; 生肖:[牛]
changed sth
输入:[1981-7-27]; 输出:[1981-6-26]; 天干地支:[辛酉-乙未-丙午]; 生肖:[雞]
changed sth
输入:[1985-5-10]; 输出:[1985-3-21]; 天干地支:[乙丑-辛巳-己酉]; 生肖:[牛]
changed sth
输入:[1978-7-17]; 输出:[1978-6-13]; 天干地支:[戊午-己未-庚辰]; 生肖:[馬]
changed sth
输入:[1974-7-16]; 输出:[1974-5-27]; 天干地支:[甲寅-辛未-戊午]; 生肖:[虎]
changed sth
输入:[1974-7-16]; 输出:[1974-5-27]; 天干地支:[甲寅-辛未-戊午]; 生肖:[虎]
changed sth
输入:[1948-1-24]; 输出:[1947-12-14]; 天干地支:[丁亥-癸丑-戊申]; 生肖:[豬]
changed sth
输入:[1948-1-24]; 输出:[1947-12-14]; 天干地支:[丁亥-癸丑-戊申]; 生肖:[豬]
changed sth
输入:[1968-9-27]; 输出:[1968-8-6]; 天干地支:[戊申-辛酉-庚子]; 生肖:[猴]
changed sth
输入:[1968-9-27]; 输出:[1968-8-6]; 天干地支:[戊申-辛酉-庚子]; 生肖:[猴]
changed sth
输入:[1965-4-6]; 输出:[1965-3-5]; 天干地支:[乙巳-庚辰-庚寅]; 生肖:[蛇]
changed sth
输入:[1963-6-1]; 输出:[1963-4-10]; 天干地支:[癸卯-丁巳-乙亥]; 生肖:[兔]
changed sth
输入:[1962-6-27]; 输出:[1962-5-26]; 天干地支:[壬寅-丙午-丙申]; 生肖:[虎]
changed sth
输入:[1952-4-23]; 输出:[1952-3-29]; 天干地支:[壬辰-甲辰-己亥]; 生肖:[龍]
changed sth
输入:[1952-4-23]; 输出:[1952-3-29]; 天干地支:[壬辰-甲辰-己亥]; 生肖:[龍]
changed sth
输入:[1953-11-19]; 输出:[1953-10-13]; 天干地支:[癸巳-癸亥-甲戌]; 生肖:[蛇]
changed sth
输入:[1945-4-21]; 输出:[1945-3-10]; 天干地支:[乙酉-庚辰-庚申]; 生肖:[雞]
changed sth
输入:[1945-4-21]; 输出:[1945-3-10]; 天干地支:[乙酉-庚辰-庚申]; 生肖:[雞]
changed sth
输入:[1963-3-23]; 输出:[1963-2-28]; 天干地支:[癸卯-乙卯-乙丑]; 生肖:[兔]
changed sth
输入:[1966-7-16]; 输出:[1966-5-28]; 天干地支:[丙午-乙未-丙子]; 生肖:[馬]
changed sth
输入:[1966-7-16]; 输出:[1966-5-28]; 天干地支:[丙午-乙未-丙子]; 生肖:[馬]
changed sth
输入:[1966-7-26]; 输出:[1966-6-9]; 天干地支:[丙午-乙未-丙戌]; 生肖:[馬]
changed sth
输入:[1963-9-1]; 输出:[1963-7-14]; 天干地支:[癸卯-庚申-丁未]; 生肖:[兔]
changed sth
输入:[1963-9-1]; 输出:[1963-7-14]; 天干地支:[癸卯-庚申-丁未]; 生肖:[兔]
changed sth
输入:[1981-6-26]; 输出:[1981-5-25]; 天干地支:[辛酉-甲午-乙亥]; 生肖:[雞]
changed sth
输入:[1983-4-9]; 输出:[1983-2-26]; 天干地支:[癸亥-丙辰-丁卯]; 生肖:[豬]
changed sth
输入:[1983-1-21]; 输出:[1982-12-8]; 天干地支:[壬戌-癸丑-己酉]; 生肖:[狗]
changed sth
输入:[1972-8-27]; 输出:[1972-7-19]; 天干地支:[壬子-戊申-庚寅]; 生肖:[鼠]
changed sth
输入:[1982-6-25]; 输出:[1982-5-5]; 天干地支:[壬戌-丙午-己卯]; 生肖:[狗]
changed sth
输入:[1981-10-1]; 输出:[1981-9-4]; 天干地支:[辛酉-丁酉-壬子]; 生肖:[雞]
changed sth
输入:[1985-9-19]; 输出:[1985-8-5]; 天干地支:[乙丑-乙酉-辛酉]; 生肖:[牛]
changed sth
输入:[1985-9-19]; 输出:[1985-8-5]; 天干地支:[乙丑-乙酉-辛酉]; 生肖:[牛]
changed sth
输入:[1991-7-7]; 输出:[1991-5-26]; 天干地支:[辛未-乙未-戊寅]; 生肖:[羊]
changed sth
输入:[1971-12-7]; 输出:[1971-10-20]; 天干地支:[辛亥-己亥-丙寅]; 生肖:[豬]
changed sth
输入:[1982-9-25]; 输出:[1982-8-9]; 天干地支:[壬戌-己酉-辛亥]; 生肖:[狗]
changed sth
输入:[1983-8-16]; 输出:[1983-7-8]; 天干地支:[癸亥-庚申-丙子]; 生肖:[豬]
changed sth
输入:[1994-10-10]; 输出:[1994-9-6]; 天干地支:[甲戌-甲戌-己巳]; 生肖:[狗]
changed sth
输入:[1994-10-10]; 输出:[1994-9-6]; 天干地支:[甲戌-甲戌-己巳]; 生肖:[狗]
changed sth
输入:[1986-8-4]; 输出:[1986-6-29]; 天干地支:[丙寅-乙未-庚辰]; 生肖:[虎]
changed sth
输入:[1986-8-4]; 输出:[1986-6-29]; 天干地支:[丙寅-乙未-庚辰]; 生肖:[虎]
changed sth
输入:[1984-5-5]; 输出:[1984-4-5]; 天干地支:[甲子-己巳-己亥]; 生肖:[鼠]
changed sth
输入:[1990-10-8]; 输出:[1990-8-20]; 天干地支:[庚午-丙戌-丙午]; 生肖:[馬]
changed sth
输入:[1990-10-8]; 输出:[1990-8-20]; 天干地支:[庚午-丙戌-丙午]; 生肖:[馬]
changed sth
输入:[1979-2-19]; 输出:[1979-1-23]; 天干地支:[己未-丙寅-丁巳]; 生肖:[羊]
changed sth
输入:[1979-2-6]; 输出:[1979-1-10]; 天干地支:[己未-丙寅-甲辰]; 生肖:[羊]
changed sth
输入:[1988-6-18]; 输出:[1988-5-5]; 天干地支:[戊辰-戊午-甲辰]; 生肖:[龍]
changed sth
输入:[1988-6-18]; 输出:[1988-5-5]; 天干地支:[戊辰-戊午-甲辰]; 生肖:[龍]
changed sth
输入:[1993-5-16]; 输出:[1993-3-25]; 天干地支:[癸酉-丁巳-丁酉]; 生肖:[雞]
changed sth
输入:[1993-5-16]; 输出:[1993-3-25]; 天干地支:[癸酉-丁巳-丁酉]; 生肖:[雞]
changed sth
输入:[1971-9-23]; 输出:[1971-8-5]; 天干地支:[辛亥-丁酉-辛亥]; 生肖:[豬]
changed sth
输入:[1987-8-25]; 输出:[1987-7-2]; 天干地支:[丁卯-戊申-丙午]; 生肖:[兔]
changed sth
输入:[1987-8-25]; 输出:[1987-7-2]; 天干地支:[丁卯-戊申-丙午]; 生肖:[兔]
changed sth
输入:[1984-9-11]; 输出:[1984-8-16]; 天干地支:[甲子-癸酉-戊申]; 生肖:[鼠]
changed sth
输入:[1984-9-11]; 输出:[1984-8-16]; 天干地支:[甲子-癸酉-戊申]; 生肖:[鼠]
changed sth
输入:[1981-10-2]; 输出:[1981-9-5]; 天干地支:[辛酉-丁酉-癸丑]; 生肖:[雞]
changed sth
输入:[1975-9-18]; 输出:[1975-8-13]; 天干地支:[乙卯-乙酉-丁卯]; 生肖:[兔]
changed sth
输入:[1975-9-18]; 输出:[1975-8-13]; 天干地支:[乙卯-乙酉-丁卯]; 生肖:[兔]
changed sth
输入:[1974-10-28]; 输出:[1974-9-14]; 天干地支:[甲寅-甲戌-壬寅]; 生肖:[虎]
changed sth
输入:[1986-1-29]; 输出:[1985-12-20]; 天干地支:[乙丑-己丑-癸酉]; 生肖:[牛]
changed sth
输入:[1976-7-1]; 输出:[1976-6-5]; 天干地支:[丙辰-甲午-甲寅]; 生肖:[龍]
changed sth
输入:[1979-10-20]; 输出:[1979-8-30]; 天干地支:[己未-甲戌-庚申]; 生肖:[羊]
changed sth
输入:[1980-11-12]; 输出:[1980-10-5]; 天干地支:[庚申-丁亥-己丑]; 生肖:[猴]
changed sth
输入:[1980-11-12]; 输出:[1980-10-5]; 天干地支:[庚申-丁亥-己丑]; 生肖:[猴]
changed sth
输入:[1976-8-2]; 输出:[1976-7-7]; 天干地支:[丙辰-乙未-丙戌]; 生肖:[龍]
changed sth
输入:[1977-6-21]; 输出:[1977-5-5]; 天干地支:[丁巳-丙午-己酉]; 生肖:[蛇]
changed sth
输入:[1973-9-13]; 输出:[1973-8-17]; 天干地支:[癸丑-辛酉-壬子]; 生肖:[牛]
changed sth
输入:[1960-8-17]; 输出:[1960-6-25]; 天干地支:[庚子-甲申-丁丑]; 生肖:[鼠]
changed sth
输入:[1960-8-17]; 输出:[1960-6-25]; 天干地支:[庚子-甲申-丁丑]; 生肖:[鼠]
changed sth
输入:[1966-8-19]; 输出:[1966-7-4]; 天干地支:[丙午-丙申-庚戌]; 生肖:[馬]
changed sth
输入:[1967-10-26]; 输出:[1967-9-23]; 天干地支:[丁未-庚戌-癸亥]; 生肖:[羊]
changed sth
输入:[1969-1-19]; 输出:[1968-12-2]; 天干地支:[戊申-乙丑-甲午]; 生肖:[猴]
changed sth
输入:[1963-7-2]; 输出:[1963-5-12]; 天干地支:[癸卯-戊午-丙午]; 生肖:[兔]
changed sth
输入:[1977-3-2]; 输出:[1977-1-13]; 天干地支:[丁巳-壬寅-戊午]; 生肖:[蛇]
changed sth
输入:[1977-3-2]; 输出:[1977-1-13]; 天干地支:[丁巳-壬寅-戊午]; 生肖:[蛇]
changed sth
输入:[1971-8-10]; 输出:[1971-6-20]; 天干地支:[辛亥-丙申-丁卯]; 生肖:[豬]
changed sth
输入:[1971-8-10]; 输出:[1971-6-20]; 天干地支:[辛亥-丙申-丁卯]; 生肖:[豬]
changed sth
输入:[1970-1-29]; 输出:[1969-12-22]; 天干地支:[己酉-丁丑-己酉]; 生肖:[雞]
changed sth
输入:[1979-3-11]; 输出:[1979-2-13]; 天干地支:[己未-丁卯-丁丑]; 生肖:[羊]
changed sth
输入:[1978-9-8]; 输出:[1978-8-6]; 天干地支:[戊午-辛酉-癸酉]; 生肖:[馬]
changed sth
输入:[1978-9-8]; 输出:[1978-8-6]; 天干地支:[戊午-辛酉-癸酉]; 生肖:[馬]
changed sth
输入:[1970-8-6]; 输出:[1970-7-5]; 天干地支:[庚戌-癸未-戊午]; 生肖:[狗]
changed sth
输入:[1970-8-6]; 输出:[1970-7-5]; 天干地支:[庚戌-癸未-戊午]; 生肖:[狗]
changed sth
输入:[1973-12-12]; 输出:[1973-11-18]; 天干地支:[癸丑-甲子-壬午]; 生肖:[牛]
changed sth
输入:[1985-9-17]; 输出:[1985-8-3]; 天干地支:[乙丑-乙酉-己未]; 生肖:[牛]
changed sth
输入:[1985-7-15]; 输出:[1985-5-28]; 天干地支:[乙丑-癸未-乙卯]; 生肖:[牛]
changed sth
输入:[1981-10-12]; 输出:[1981-9-15]; 天干地支:[辛酉-戊戌-癸亥]; 生肖:[雞]
changed sth
输入:[1992-2-1]; 输出:[1991-12-28]; 天干地支:[辛未-辛丑-丁未]; 生肖:[羊]
changed sth
输入:[1975-4-6]; 输出:[1975-2-25]; 天干地支:[乙卯-庚辰-壬午]; 生肖:[兔]
changed sth
输入:[1998-1-24]; 输出:[1997-12-26]; 天干地支:[丁丑-癸丑-辛未]; 生肖:[牛]
changed sth
输入:[1996-6-1]; 输出:[1996-4-16]; 天干地支:[丙子-癸巳-己巳]; 生肖:[鼠]
changed sth
输入:[1991-12-23]; 输出:[1991-11-18]; 天干地支:[辛未-庚子-丁卯]; 生肖:[羊]
changed sth
输入:[1991-12-23]; 输出:[1991-11-18]; 天干地支:[辛未-庚子-丁卯]; 生肖:[羊]
changed sth
输入:[2000-5-16]; 输出:[2000-4-13]; 天干地支:[庚辰-辛巳-甲戌]; 生肖:[龍]
changed sth
输入:[2000-5-16]; 输出:[2000-4-13]; 天干地支:[庚辰-辛巳-甲戌]; 生肖:[龍]
changed sth
输入:[1998-9-6]; 输出:[1998-7-16]; 天干地支:[戊寅-庚申-丙辰]; 生肖:[虎]
changed sth
输入:[1998-9-6]; 输出:[1998-7-16]; 天干地支:[戊寅-庚申-丙辰]; 生肖:[虎]
changed sth
输入:[2002-5-24]; 输出:[2002-4-13]; 天干地支:[壬午-乙巳-壬辰]; 生肖:[馬]
changed sth
输入:[1996-9-12]; 输出:[1996-7-30]; 天干地支:[丙子-丁酉-壬子]; 生肖:[鼠]
changed sth
输入:[1993-9-13]; 输出:[1993-7-27]; 天干地支:[癸酉-辛酉-丁酉]; 生肖:[雞]
changed sth
输入:[1993-9-13]; 输出:[1993-7-27]; 天干地支:[癸酉-辛酉-丁酉]; 生肖:[雞]
changed sth
输入:[1999-3-4]; 输出:[1999-1-17]; 天干地支:[己卯-丙寅-乙卯]; 生肖:[兔]
changed sth
输入:[1999-3-4]; 输出:[1999-1-17]; 天干地支:[己卯-丙寅-乙卯]; 生肖:[兔]
changed sth
输入:[1993-12-20]; 输出:[1993-11-8]; 天干地支:[癸酉-甲子-乙亥]; 生肖:[雞]
changed sth
输入:[1993-12-20]; 输出:[1993-11-8]; 天干地支:[癸酉-甲子-乙亥]; 生肖:[雞]
changed sth
输入:[2002-10-2]; 输出:[2002-8-26]; 天干地支:[壬午-己酉-癸卯]; 生肖:[馬]
changed sth
输入:[2002-10-2]; 输出:[2002-8-26]; 天干地支:[壬午-己酉-癸卯]; 生肖:[馬]
changed sth
输入:[1995-11-2]; 输出:[1995-9-10]; 天干地支:[乙亥-丙戌-丁酉]; 生肖:[豬]
changed sth
输入:[1995-11-2]; 输出:[1995-9-10]; 天干地支:[乙亥-丙戌-丁酉]; 生肖:[豬]
changed sth
输入:[1989-3-11]; 输出:[1989-2-4]; 天干地支:[己巳-丁卯-庚午]; 生肖:[蛇]
changed sth
输入:[1989-3-11]; 输出:[1989-2-4]; 天干地支:[己巳-丁卯-庚午]; 生肖:[蛇]
changed sth
输入:[1999-3-4]; 输出:[1999-1-17]; 天干地支:[己卯-丙寅-乙卯]; 生肖:[兔]
changed sth
输入:[1999-3-4]; 输出:[1999-1-17]; 天干地支:[己卯-丙寅-乙卯]; 生肖:[兔]
changed sth
输入:[1985-9-19]; 输出:[1985-8-5]; 天干地支:[乙丑-乙酉-辛酉]; 生肖:[牛]
changed sth
输入:[1977-3-2]; 输出:[1977-1-13]; 天干地支:[丁巳-壬寅-戊午]; 生肖:[蛇]
changed sth
输入:[1972-8-15]; 输出:[1972-7-7]; 天干地支:[壬子-戊申-戊寅]; 生肖:[鼠]
changed sth
输入:[1975-8-6]; 输出:[1975-6-29]; 天干地支:[乙卯-癸未-甲申]; 生肖:[兔]
changed sth
输入:[1985-7-15]; 输出:[1985-5-28]; 天干地支:[乙丑-癸未-乙卯]; 生肖:[牛]
changed sth
输入:[1993-9-13]; 输出:[1993-7-27]; 天干地支:[癸酉-辛酉-丁酉]; 生肖:[雞]
changed sth
输入:[1993-9-13]; 输出:[1993-7-27]; 天干地支:[癸酉-辛酉-丁酉]; 生肖:[雞]
changed sth
输入:[1982-10-28]; 输出:[1982-9-12]; 天干地支:[壬戌-庚戌-甲申]; 生肖:[狗]
changed sth
输入:[1982-10-28]; 输出:[1982-9-12]; 天干地支:[壬戌-庚戌-甲申]; 生肖:[狗]
changed sth
输入:[1993-1-29]; 输出:[1992-1-7]; 天干地支:[壬申-癸丑-庚戌]; 生肖:[猴]
changed sth
输入:[1985-1-1]; 输出:[1984-11-11]; 天干地支:[甲子-丙子-庚子]; 生肖:[鼠]
changed sth
输入:[1999-3-4]; 输出:[1999-1-17]; 天干地支:[己卯-丙寅-乙卯]; 生肖:[兔]
changed sth
输入:[1997-7-26]; 输出:[1997-6-22]; 天干地支:[丁丑-丁未-己巳]; 生肖:[牛]
changed sth
输入:[1997-7-26]; 输出:[1997-6-22]; 天干地支:[丁丑-丁未-己巳]; 生肖:[牛]
changed sth
输入:[1999-5-27]; 输出:[1999-4-13]; 天干地支:[己卯-己巳-己卯]; 生肖:[兔]
changed sth
输入:[1999-5-27]; 输出:[1999-4-13]; 天干地支:[己卯-己巳-己卯]; 生肖:[兔]
changed sth
输入:[1992-7-1]; 输出:[1992-6-2]; 天干地支:[壬申-丙午-戊寅]; 生肖:[猴]
changed sth
输入:[1970-4-10]; 输出:[1970-3-5]; 天干地支:[庚戌-庚辰-庚申]; 生肖:[狗]
changed sth
输入:[1987-1-17]; 输出:[1986-12-18]; 天干地支:[丙寅-辛丑-丙寅]; 生肖:[虎]
changed sth
输入:[1984-1-29]; 输出:[1983-12-27]; 天干地支:[癸亥-乙丑-壬戌]; 生肖:[豬]
changed sth
输入:[1968-3-2]; 输出:[1968-2-4]; 天干地支:[戊申-甲寅-辛未]; 生肖:[猴]
changed sth
输入:[1967-11-13]; 输出:[1967-10-12]; 天干地支:[丁未-辛亥-辛巳]; 生肖:[羊]
changed sth
输入:[1966-8-27]; 输出:[1966-7-12]; 天干地支:[丙午-丙申-戊午]; 生肖:[馬]
changed sth
changed sth
输入:[1960-11-23]; 输出:[1960-10-5]; 天干地支:[庚子-丁亥-乙卯]; 生肖:[鼠]
changed sth
输入:[1971-9-1]; 输出:[1971-7-12]; 天干地支:[辛亥-丙申-己丑]; 生肖:[豬]
changed sth
输入:[1970-1-25]; 输出:[1969-12-18]; 天干地支:[己酉-丁丑-乙巳]; 生肖:[雞]
changed sth
输入:[1971-8-10]; 输出:[1971-6-20]; 天干地支:[辛亥-丙申-丁卯]; 生肖:[豬]
changed sth
输入:[1971-8-10]; 输出:[1971-6-20]; 天干地支:[辛亥-丙申-丁卯]; 生肖:[豬]
changed sth
输入:[1968-12-1]; 输出:[1968-10-12]; 天干地支:[戊申-癸亥-乙巳]; 生肖:[猴]
changed sth
输入:[1960-7-12]; 输出:[1960-6-19]; 天干地支:[庚子-癸未-辛丑]; 生肖:[鼠]
changed sth
输入:[1963-7-23]; 输出:[1963-6-3]; 天干地支:[癸卯-己未-丁卯]; 生肖:[兔]
changed sth
输入:[1986-11-14]; 输出:[1986-10-13]; 天干地支:[丙寅-己亥-壬戌]; 生肖:[虎]
changed sth
输入:[1981-7-6]; 输出:[1981-6-5]; 天干地支:[辛酉-甲午-乙酉]; 生肖:[雞]
changed sth
输入:[1974-12-2]; 输出:[1974-10-19]; 天干地支:[甲寅-乙亥-丁丑]; 生肖:[虎]
changed sth
输入:[1974-12-2]; 输出:[1974-10-19]; 天干地支:[甲寅-乙亥-丁丑]; 生肖:[虎]
changed sth
输入:[1978-1-20]; 输出:[1977-12-12]; 天干地支:[丁巳-癸丑-壬午]; 生肖:[蛇]
changed sth
输入:[1980-4-8]; 输出:[1980-2-23]; 天干地支:[庚申-庚辰-辛亥]; 生肖:[猴]
changed sth
输入:[1980-4-8]; 输出:[1980-2-23]; 天干地支:[庚申-庚辰-辛亥]; 生肖:[猴]
changed sth
输入:[1982-12-24]; 输出:[1982-11-10]; 天干地支:[壬戌-壬子-辛巳]; 生肖:[狗]
changed sth
输入:[1983-12-2]; 输出:[1983-10-28]; 天干地支:[癸亥-癸亥-甲子]; 生肖:[豬]
changed sth
输入:[1979-11-29]; 输出:[1979-10-10]; 天干地支:[己未-乙亥-庚子]; 生肖:[羊]
changed sth
输入:[1979-11-29]; 输出:[1979-10-10]; 天干地支:[己未-乙亥-庚子]; 生肖:[羊]
changed sth
输入:[1980-8-26]; 输出:[1980-7-16]; 天干地支:[庚申-甲申-辛未]; 生肖:[猴]
changed sth
输入:[1980-8-26]; 输出:[1980-7-16]; 天干地支:[庚申-甲申-辛未]; 生肖:[猴]
changed sth
输入:[1993-11-9]; 输出:[1993-9-26]; 天干地支:[癸酉-癸亥-甲午]; 生肖:[雞]
changed sth
输入:[1993-11-9]; 输出:[1993-9-26]; 天干地支:[癸酉-癸亥-甲午]; 生肖:[雞]
changed sth
输入:[1969-9-5]; 输出:[1969-7-24]; 天干地支:[己酉-壬申-癸未]; 生肖:[雞]
changed sth
输入:[1969-9-5]; 输出:[1969-7-24]; 天干地支:[己酉-壬申-癸未]; 生肖:[雞]
changed sth
输入:[1973-8-3]; 输出:[1973-7-5]; 天干地支:[癸丑-己未-辛未]; 生肖:[牛]
changed sth
输入:[1973-8-3]; 输出:[1973-7-5]; 天干地支:[癸丑-己未-辛未]; 生肖:[牛]
changed sth
输入:[1965-9-10]; 输出:[1965-8-15]; 天干地支:[乙巳-乙酉-丁卯]; 生肖:[蛇]
changed sth
输入:[1969-4-20]; 输出:[1969-3-4]; 天干地支:[己酉-戊辰-乙丑]; 生肖:[雞]
changed sth
输入:[1966-10-20]; 输出:[1966-9-7]; 天干地支:[丙午-戊戌-壬子]; 生肖:[馬]
changed sth
输入:[1966-10-20]; 输出:[1966-9-7]; 天干地支:[丙午-戊戌-壬子]; 生肖:[馬]
changed sth
输入:[1971-9-15]; 输出:[1971-7-26]; 天干地支:[辛亥-丁酉-癸卯]; 生肖:[豬]
changed sth
输入:[1971-9-15]; 输出:[1971-7-26]; 天干地支:[辛亥-丁酉-癸卯]; 生肖:[豬]
changed sth
输入:[1980-11-12]; 输出:[1980-10-5]; 天干地支:[庚申-丁亥-己丑]; 生肖:[猴]
changed sth
changed sth
changed sth
changed sth
changed sth
输入:[1979-8-10]; 输出:[1979-6-18]; 天干地支:[己未-壬申-己酉]; 生肖:[羊]
changed sth
输入:[1968-7-8]; 输出:[1968-6-13]; 天干地支:[戊申-己未-己卯]; 生肖:[猴]
changed sth
输入:[1968-7-8]; 输出:[1968-6-13]; 天干地支:[戊申-己未-己卯]; 生肖:[猴]
changed sth
输入:[1969-8-11]; 输出:[1969-6-29]; 天干地支:[己酉-壬申-戊午]; 生肖:[雞]
changed sth
输入:[1969-8-11]; 输出:[1969-6-29]; 天干地支:[己酉-壬申-戊午]; 生肖:[雞]
changed sth
输入:[1962-5-28]; 输出:[1962-4-25]; 天干地支:[壬寅-乙巳-丙寅]; 生肖:[虎]
changed sth
输入:[1969-8-18]; 输出:[1969-7-6]; 天干地支:[己酉-壬申-乙丑]; 生肖:[雞]
changed sth
输入:[1969-8-18]; 输出:[1969-7-6]; 天干地支:[己酉-壬申-乙丑]; 生肖:[雞]
changed sth
输入:[1955-1-18]; 输出:[1954-12-25]; 天干地支:[甲午-丁丑-己卯]; 生肖:[馬]
changed sth
输入:[1955-1-18]; 输出:[1954-12-25]; 天干地支:[甲午-丁丑-己卯]; 生肖:[馬]
changed sth
输入:[1963-12-18]; 输出:[1963-11-3]; 天干地支:[癸卯-甲子-乙未]; 生肖:[兔]
changed sth
输入:[1963-12-18]; 输出:[1963-11-3]; 天干地支:[癸卯-甲子-乙未]; 生肖:[兔]
changed sth
输入:[1955-8-4]; 输出:[1955-6-17]; 天干地支:[乙未-癸未-丁酉]; 生肖:[羊]
changed sth
输入:[1955-8-4]; 输出:[1955-6-17]; 天干地支:[乙未-癸未-丁酉]; 生肖:[羊]
changed sth
输入:[1972-11-1]; 输出:[1972-9-26]; 天干地支:[壬子-庚戌-丙申]; 生肖:[鼠]
changed sth
输入:[1972-11-1]; 输出:[1972-9-26]; 天干地支:[壬子-庚戌-丙申]; 生肖:[鼠]
changed sth
输入:[1986-4-14]; 输出:[1986-3-6]; 天干地支:[丙寅-壬辰-戊子]; 生肖:[虎]
changed sth
输入:[1979-3-19]; 输出:[1979-2-21]; 天干地支:[己未-丁卯-乙酉]; 生肖:[羊]
changed sth
输入:[1985-6-12]; 输出:[1985-4-24]; 天干地支:[乙丑-壬午-壬午]; 生肖:[牛]
changed sth
输入:[1978-5-3]; 输出:[1978-3-27]; 天干地支:[戊午-丙辰-乙丑]; 生肖:[馬]
changed sth
输入:[1977-4-2]; 输出:[1977-2-14]; 天干地支:[丁巳-癸卯-己丑]; 生肖:[蛇]
changed sth
输入:[1977-4-2]; 输出:[1977-2-14]; 天干地支:[丁巳-癸卯-己丑]; 生肖:[蛇]
changed sth
输入:[1982-8-24]; 输出:[1982-7-6]; 天干地支:[壬戌-戊申-己卯]; 生肖:[狗]
changed sth
输入:[1976-10-7]; 输出:[1976-8-14]; 天干地支:[丙辰-丁酉-壬辰]; 生肖:[龍]
changed sth
输入:[1974-12-29]; 输出:[1974-11-16]; 天干地支:[甲寅-丙子-甲辰]; 生肖:[虎]
changed sth
输入:[1974-12-29]; 输出:[1974-11-16]; 天干地支:[甲寅-丙子-甲辰]; 生肖:[虎]
changed sth
输入:[1980-8-21]; 输出:[1980-7-11]; 天干地支:[庚申-甲申-丙寅]; 生肖:[猴]
changed sth
输入:[1980-8-21]; 输出:[1980-7-11]; 天干地支:[庚申-甲申-丙寅]; 生肖:[猴]
changed sth
输入:[1979-1-10]; 输出:[1978-12-12]; 天干地支:[戊午-乙丑-丁丑]; 生肖:[馬]
changed sth
输入:[1979-6-1]; 输出:[1979-5-7]; 天干地支:[己未-己巳-己亥]; 生肖:[羊]
changed sth
输入:[1980-7-2]; 输出:[1980-5-20]; 天干地支:[庚申-壬午-丙子]; 生肖:[猴]
changed sth
输入:[1980-7-2]; 输出:[1980-5-20]; 天干地支:[庚申-壬午-丙子]; 生肖:[猴]
changed sth
输入:[1972-8-15]; 输出:[1972-7-7]; 天干地支:[壬子-戊申-戊寅]; 生肖:[鼠]
changed sth
输入:[1972-8-15]; 输出:[1972-7-7]; 天干地支:[壬子-戊申-戊寅]; 生肖:[鼠]
changed sth
输入:[1960-11-21]; 输出:[1960-10-3]; 天干地支:[庚子-丁亥-癸丑]; 生肖:[鼠]
changed sth
输入:[1966-9-12]; 输出:[1966-7-28]; 天干地支:[丙午-丁酉-甲戌]; 生肖:[馬]
changed sth
输入:[1966-9-12]; 输出:[1966-7-28]; 天干地支:[丙午-丁酉-甲戌]; 生肖:[馬]
changed sth
输入:[1969-1-22]; 输出:[1968-12-5]; 天干地支:[戊申-乙丑-丁酉]; 生肖:[猴]
changed sth
输入:[1979-4-11]; 输出:[1979-3-15]; 天干地支:[己未-戊辰-戊申]; 生肖:[羊]
changed sth
输入:[1967-10-4]; 输出:[1967-9-1]; 天干地支:[丁未-己酉-辛丑]; 生肖:[羊]
changed sth
输入:[1967-10-4]; 输出:[1967-9-1]; 天干地支:[丁未-己酉-辛丑]; 生肖:[羊]
changed sth
输入:[1944-9-1]; 输出:[1944-7-14]; 天干地支:[甲申-壬申-戊辰]; 生肖:[猴]
changed sth
输入:[1946-8-2]; 输出:[1946-7-6]; 天干地支:[丙戌-乙未-戊申]; 生肖:[狗]
changed sth
输入:[1940-4-25]; 输出:[1940-3-18]; 天干地支:[庚辰-庚辰-戊戌]; 生肖:[龍]
changed sth
输入:[1940-4-25]; 输出:[1940-3-18]; 天干地支:[庚辰-庚辰-戊戌]; 生肖:[龍]
changed sth
输入:[1951-3-17]; 输出:[1951-2-10]; 天干地支:[辛卯-辛卯-丙辰]; 生肖:[兔]
changed sth
输入:[1938-11-19]; 输出:[1938-9-28]; 天干地支:[戊寅-癸亥-乙卯]; 生肖:[虎]
changed sth
输入:[1938-11-19]; 输出:[1938-9-28]; 天干地支:[戊寅-癸亥-乙卯]; 生肖:[虎]
changed sth
输入:[1958-10-16]; 输出:[1958-9-4]; 天干地支:[戊戌-壬戌-丙寅]; 生肖:[狗]
changed sth
输入:[1958-10-16]; 输出:[1958-9-4]; 天干地支:[戊戌-壬戌-丙寅]; 生肖:[狗]
changed sth
输入:[1956-4-5]; 输出:[1956-2-25]; 天干地支:[丙申-壬辰-壬寅]; 生肖:[猴]
changed sth
输入:[1954-8-16]; 输出:[1954-7-18]; 天干地支:[甲午-壬申-甲辰]; 生肖:[馬]
changed sth
输入:[1954-8-16]; 输出:[1954-7-18]; 天干地支:[甲午-壬申-甲辰]; 生肖:[馬]
changed sth
输入:[1965-1-2]; 输出:[1964-11-30]; 天干地支:[甲辰-丙子-丙辰]; 生肖:[龍]
changed sth
输入:[1973-8-10]; 输出:[1973-7-12]; 天干地支:[癸丑-庚申-戊寅]; 生肖:[牛]
changed sth
输入:[1978-12-10]; 输出:[1978-11-11]; 天干地支:[戊午-甲子-丙午]; 生肖:[馬]
changed sth
输入:[1978-9-3]; 输出:[1978-8-1]; 天干地支:[戊午-庚申-戊辰]; 生肖:[馬]
changed sth
输入:[1978-9-3]; 输出:[1978-8-1]; 天干地支:[戊午-庚申-戊辰]; 生肖:[馬]
changed sth
输入:[1982-6-29]; 输出:[1982-5-9]; 天干地支:[壬戌-丙午-癸未]; 生肖:[狗]
changed sth
输入:[1943-1-19]; 输出:[1942-12-14]; 天干地支:[壬午-癸丑-丁丑]; 生肖:[馬]
changed sth
输入:[1969-7-5]; 输出:[1969-5-21]; 天干地支:[己酉-庚午-辛巳]; 生肖:[雞]
changed sth
输入:[1969-7-5]; 输出:[1969-5-21]; 天干地支:[己酉-庚午-辛巳]; 生肖:[雞]
changed sth
输入:[1969-5-19]; 输出:[1969-4-4]; 天干地支:[己酉-己巳-甲午]; 生肖:[雞]
changed sth
输入:[1970-5-4]; 输出:[1970-3-29]; 天干地支:[庚戌-庚辰-甲申]; 生肖:[狗]
changed sth
输入:[1970-5-4]; 输出:[1970-3-29]; 天干地支:[庚戌-庚辰-甲申]; 生肖:[狗]
changed sth
输入:[1980-11-1]; 输出:[1980-9-24]; 天干地支:[庚申-丙戌-戊寅]; 生肖:[猴]
changed sth
输入:[1971-6-2]; 输出:[1971-5-10]; 天干地支:[辛亥-癸巳-戊午]; 生肖:[豬]
changed sth
输入:[1973-1-30]; 输出:[1972-12-27]; 天干地支:[壬子-癸丑-丙寅]; 生肖:[鼠]
changed sth
输入:[1970-8-21]; 输出:[1970-7-20]; 天干地支:[庚戌-甲申-癸酉]; 生肖:[狗]
changed sth
输入:[1967-12-20]; 输出:[1967-11-19]; 天干地支:[丁未-壬子-戊午]; 生肖:[羊]
changed sth
输入:[1967-12-20]; 输出:[1967-11-19]; 天干地支:[丁未-壬子-戊午]; 生肖:[羊]
changed sth
输入:[1977-2-20]; 输出:[1977-1-3]; 天干地支:[丁巳-壬寅-戊申]; 生肖:[蛇]
changed sth
输入:[1977-2-20]; 输出:[1977-1-3]; 天干地支:[丁巳-壬寅-戊申]; 生肖:[蛇]
changed sth
输入:[1954-5-16]; 输出:[1954-4-14]; 天干地支:[甲午-己巳-壬申]; 生肖:[馬]

In [15]:
#drop rows with null values in bazi_man

man_df.dropna(subset=['bazi_man'], inplace=True)
man_df

            Male_name male_birthdate  Year Event                  bazi_man
0    Ryan Reynolds    1976-02-23      2011  1     [丙, 辰, 庚, 寅, 乙, 巳, 丙, 子]
1    Colin Jost       1982-06-20      2017  1     [壬, 戌, 丙, 午, 甲, 戌, 甲, 子]
2    Nick Jonas       1992-09-16      2018  1     [壬, 申, 己, 酉, 乙, 未, 丙, 子]
3    Prince Harry     1984-09-15      2016  1     [甲, 子, 癸, 酉, 壬, 子, 庚, 子]
4    George Clooney   1961-06-05      2014  1     [辛, 丑, 癸, 巳, 己, 巳, 甲, 子]
..              ...          ...       ... ..                          ...
321  Franchot Tone    1903-05-27      1939  0     [癸, 卯, 丁, 巳, 乙, 卯, 丙, 子]
322  Cooke Maroney    1984-06-04      2018  1     [甲, 子, 己, 巳, 己, 巳, 甲, 子]
323  Brooklyn Beckham 1999-03-04      2019  1     [己, 卯, 丙, 寅, 乙, 卯, 丙, 子]
324  Lily-Rose Depp   1999-05-27      2018  1     [己, 卯, 己, 巳, 己, 卯, 甲, 子]
325  Lily-Rose Depp   1999-05-27      2020  0     [己, 卯, 己, 巳, 己, 卯, 甲, 子]

[315 rows x 5 columns]

In [16]:
import numpy as np

man_df[['man年干', 'man年支', 'man月干', 'man月支', 'man日干', 'man日支', 'man時干', 'man時支']] = man_df['bazi_man'].apply(lambda x: [x[0], x[1], x[2], x[3], x[4], x[5], x[6], x[7]] if x is not None else [np.nan]*8).apply(pd.Series)

In [17]:
man_df

,Male_name,male_birthdate,Year,Event,bazi_man,man年干,man年支,man月干,man月支,man日干,man日支,man時干,man時支
0,Ryan Reynolds,1976-02-23,2011,1,"[丙, 辰, 庚, 寅, 乙, 巳, 丙, 子]",丙,辰,庚,寅,乙,巳,丙,子
1,Colin Jost,1982-06-20,2017,1,"[壬, 戌, 丙, 午, 甲, 戌, 甲, 子]",壬,戌,丙,午,甲,戌,甲,子
2,Nick Jonas,1992-09-16,2018,1,"[壬, 申, 己, 酉, 乙, 未, 丙, 子]",壬,申,己,酉,乙,未,丙,子
3,Prince Harry,1984-09-15,2016,1,"[甲, 子, 癸, 酉, 壬, 子, 庚, 子]",甲,子,癸,酉,壬,子,庚,子
4,George Clooney,1961-06-05,2014,1,"[辛, 丑, 癸, 巳, 己, 巳, 甲, 子]",辛,丑,癸,巳,己,巳,甲,子
...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,Franchot Tone,1903-05-27,1939,0,"[癸, 卯, 丁, 巳, 乙, 卯, 丙, 子]",癸,卯,丁,巳,乙,卯,丙,子
322,Cooke Maroney,1984-06-04,2018,1,"[甲, 子, 己, 巳, 己, 巳, 甲, 子]",甲,子,己,巳,己,巳,甲,子
323,Brooklyn Beckham,1999-03-04,2019,1,"[己, 卯, 丙, 寅, 乙, 卯, 丙, 子]",己,卯,丙,寅,乙,卯,丙,子
324,Lily-Rose Depp,1999-05-27,2018,1,"[己, 卯, 己, 巳, 己, 卯, 甲, 子]",己,卯,己,巳,己,卯,甲,子
325,Lily-Rose Depp,1999-05-27,2020,0,"[己, 卯, 己, 巳, 己, 卯, 甲, 子]",己,卯,己,巳,己,卯,甲,子

In [18]:
def getGanzhi(year):
    gan = '甲乙丙丁戊己庚辛壬癸'
    zhi = '子丑寅卯辰巳午未申酉戌亥'
    offset = 4  # the year 庚子 starts in 2020
    stem = gan[(year - offset) % 10]
    branch = zhi[(year - offset) % 12]
    return stem + branch
getGanzhi(1993)
#create new column named Year_marriage_ganzhi
man_df['Year_genzi'] = man_df['Year'].apply(lambda x: getGanzhi(x))
man_df

,Male_name,male_birthdate,Year,Event,bazi_man,man年干,man年支,man月干,man月支,man日干,man日支,man時干,man時支,Year_genzi
0,Ryan Reynolds,1976-02-23,2011,1,"[丙, 辰, 庚, 寅, 乙, 巳, 丙, 子]",丙,辰,庚,寅,乙,巳,丙,子,辛卯
1,Colin Jost,1982-06-20,2017,1,"[壬, 戌, 丙, 午, 甲, 戌, 甲, 子]",壬,戌,丙,午,甲,戌,甲,子,丁酉
2,Nick Jonas,1992-09-16,2018,1,"[壬, 申, 己, 酉, 乙, 未, 丙, 子]",壬,申,己,酉,乙,未,丙,子,戊戌
3,Prince Harry,1984-09-15,2016,1,"[甲, 子, 癸, 酉, 壬, 子, 庚, 子]",甲,子,癸,酉,壬,子,庚,子,丙申
4,George Clooney,1961-06-05,2014,1,"[辛, 丑, 癸, 巳, 己, 巳, 甲, 子]",辛,丑,癸,巳,己,巳,甲,子,甲午
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,Franchot Tone,1903-05-27,1939,0,"[癸, 卯, 丁, 巳, 乙, 卯, 丙, 子]",癸,卯,丁,巳,乙,卯,丙,子,己卯
322,Cooke Maroney,1984-06-04,2018,1,"[甲, 子, 己, 巳, 己, 巳, 甲, 子]",甲,子,己,巳,己,巳,甲,子,戊戌
323,Brooklyn Beckham,1999-03-04,2019,1,"[己, 卯, 丙, 寅, 乙, 卯, 丙, 子]",己,卯,丙,寅,乙,卯,丙,子,己亥
324,Lily-Rose Depp,1999-05-27,2018,1,"[己, 卯, 己, 巳, 己, 卯, 甲, 子]",己,卯,己,巳,己,卯,甲,子,戊戌
325,Lily-Rose Depp,1999-05-27,2020,0,"[己, 卯, 己, 巳, 己, 卯, 甲, 子]",己,卯,己,巳,己,卯,甲,子,庚子

## 定身強弱

In [19]:
#定身強弱
sanhui = {
    '木': ['寅', '卯', '辰'],
    '火': ['巳', '午', '未'],
    '金': ['申', '酉', '戌'],
    '水': ['亥', '子', '丑'],
    '土': [ '辰','戌','丑','未' ]
}

sanhe = {
    '火': ['寅', '午', '戌'],
    '水': ['申', '子', '辰'],
    '金': ['巳', '酉', '丑'],
    '木': ['亥', '卯', '未'],
    '土': [ '辰','戌','丑','未' ]
}

def 強弱得令(man日干,man月支):
    if man月支 in sanhui[wu_xing_dict[man日干]]:
        return True
    else:
        return False
    
def 強弱得地(man日干,man日支,man年支):
    wx=wu_xing_dict[man日干]
    if wx==wu_xing_dict[man日支] and wx==wu_xing_dict[man年支]:
        return True
    else:
        return False

def 強弱得勢(man日干,man月干,man年干):
    wx=wu_xing_dict[man日干]
    if wx==wu_xing_dict[man月干] or wx==wu_xing_dict[man年干]:
        return True
    else:
        return False

# def 地支半三合(man日干,man日支,man月支,man年支):
    # wx=wu_xing_dict[man日干]
    # if any of two from (man日支,man月支,man年支) are distinct and in sanhui[wx], then true


# def 地支三合(man日干,man日支,man月支,man年支):
#     wx=wu_xing_dict[man日干]
    # if all man日支,man月支,man年支 are distinct and in sanhui[wx], then true


def 強弱地支半三合(man日干, man日支, man月支, man年支):
    wx = wu_xing_dict[man日干]
    zodiacs = sanhe[wx]
    distinct_zodiacs = {man日支, man月支, man年支}
    common_zodiacs = set(zodiacs).intersection(distinct_zodiacs)
    return len(common_zodiacs) >= 2


def 強弱地支三合(man日干, man日支, man月支, man年支):
    wx = wu_xing_dict[man日干]
    zodiacs = sanhe[wx]
    distinct_zodiacs = {man日支, man月支, man年支}
    return distinct_zodiacs.issubset(zodiacs) and len(distinct_zodiacs) == 3

def 強弱地支半三會(man日干, man日支, man月支, man年支):
    wx = wu_xing_dict[man日干]
    zodiacs = sanhui[wx]
    distinct_zodiacs = {man日支, man月支, man年支}
    common_zodiacs = set(zodiacs).intersection(distinct_zodiacs)
    return len(common_zodiacs) >= 2


def 強弱地支三會(man日干, man日支, man月支, man年支):
    wx = wu_xing_dict[man日干]
    zodiacs = sanhui[wx]
    distinct_zodiacs = {man日支, man月支, man年支}
    return distinct_zodiacs.issubset(zodiacs) and len(distinct_zodiacs) == 3

sheng_dict = {
    '金': ['水'],
    '木': ['火'],
    '水': ['木'],
    '火': ['土'],
    '土': ['金']
}
# def 印的數量(man日干, man日支, man月干,man月支, man年干,man年支):
    # if man日支, man月干,man月支, man年干,man年支 are 印 of man日干, then return 5
    # if sheng_dict[man日支] == wu_xing_dict[man日干], then it is 印

def 強弱印的數量(man日干, man日支, man月干, man月支, man年干, man年支):

    count = 0
    if sheng_dict[wu_xing_dict[man日支]] == wu_xing_dict[man日干]:
        count += 1
    if sheng_dict[wu_xing_dict[man月干]] == wu_xing_dict[man日干]:
        count += 1
    if sheng_dict[wu_xing_dict[man月支]] == wu_xing_dict[man日干]:
        count += 1
    if sheng_dict[wu_xing_dict[man年干]] == wu_xing_dict[man日干]:
        count += 1
    if sheng_dict[wu_xing_dict[man年支]] == wu_xing_dict[man日干]:
        count += 1
    return count


import pandas as pd

# Assuming you have a DataFrame called man_df with the relevant columns

man_df['強弱得令'] = man_df.apply(lambda row: 強弱得令(row['man日干'], row['man月支']), axis=1)
man_df['強弱地支三會'] = man_df.apply(lambda row: 強弱地支三會(row['man日干'], row['man日支'], row['man月支'], row['man年支']), axis=1)
man_df['強弱地支三合'] = man_df.apply(lambda row: 強弱地支三合(row['man日干'], row['man日支'], row['man月支'], row['man年支']), axis=1)
man_df['強弱得地'] = man_df.apply(lambda row: 強弱得地(row['man日干'], row['man日支'], row['man年支']), axis=1)
man_df['強弱得勢'] = man_df.apply(lambda row: 強弱得勢(row['man日干'], row['man月干'], row['man年干']), axis=1)
man_df['強弱地支半三合'] = man_df.apply(lambda row: 強弱地支半三合(row['man日干'], row['man日支'], row['man月支'], row['man年支']), axis=1)
man_df['強弱地支半三會'] = man_df.apply(lambda row: 強弱地支半三會(row['man日干'], row['man日支'], row['man月支'], row['man年支']), axis=1)

man_df['強弱印的數量'] = man_df.apply(lambda row: 強弱印的數量(row['man日干'], row['man日支'], row['man月干'], row['man月支'], row['man年干'], row['man年支']), axis=1)

# Assuming 'man日干', 'man日支', 'man月支', 'man年支', 'man月干', 'man年干' are column names in the DataFrame


#create new col named 身強身弱
# if 強弱得令 is true,  then 身強身弱 is 強 
# elif 強弱地支三會 is true,  then 身強身弱 is 強
# elif 強弱地支三合 is true,  then 身強身弱 is 強
# elif 強弱印的數量 is 4,  then 身強身弱 is 強
# elif 強弱地支半三會 is true,  then 身強身弱 is 可能強
# elif 強弱地支半三合 is true,  then 身強身弱 is 可能強
# elif 強弱印的數量 is 3,  then 身強身弱 is 可能強
# elif 強弱得地 is true,  then 身強身弱 is 可能強 
# elif 強弱得勢 is true,  then 身強身弱 is 可能強
# else 身強身弱 is 弱

man_df['身強身弱'] = ''

for index, row in man_df.iterrows():
    if row['強弱得令']:
        man_df.at[index, '身強身弱'] = '強'
    elif row['強弱地支三會']:
        man_df.at[index, '身強身弱'] = '強'
    elif row['強弱地支三合']:
        man_df.at[index, '身強身弱'] = '強'
    elif 強弱印的數量(row['man日干'], row['man日支'], row['man月干'], row['man月支'], row['man年干'], row['man年支']) == 4:
        man_df.at[index, '身強身弱'] = '強'
    elif row['強弱地支半三會']:
        man_df.at[index, '身強身弱'] = '可能強'
    elif row['強弱地支半三合']:
        man_df.at[index, '身強身弱'] = '可能強'
    elif 強弱印的數量(row['man日干'], row['man日支'], row['man月干'], row['man月支'], row['man年干'], row['man年支']) == 3:
        man_df.at[index, '身強身弱'] = '可能強'
    elif row['強弱得地']:
        man_df.at[index, '身強身弱'] = '可能強'
    elif row['強弱得勢']:
        man_df.at[index, '身強身弱'] = '可能強'
    else:
        man_df.at[index, '身強身弱'] = '弱'

## liunian combination

In [20]:
# 流年地支=Year_genzi[1]
# 流年天干=Year_genzi[0]
#日支伏吟
#if Year_genzi[1] equal man日支, then True, else False, and create new column named man日支同年支
man_df['man日支同年支'] = man_df.apply(lambda row: True if row['man日支'] == row['Year_genzi'][1] else False, axis=1)
man_df
#日支六沖
#if man日支 and 流年支 is liuchong, then True, else False, and create new column named man日支六沖
man_df['man日支六沖'] = man_df.apply(lambda row: is_liuchong(row['man日支'], row['Year_genzi'][1]), axis=1)


#日支六合
#if man日支 and 流年支 is_liuhe, then True, else False, and create new column named man日支六合
man_df['man日支六合'] = man_df.apply(lambda row: is_liuhe(row['man日支'], row['Year_genzi'][1]), axis=1)

# 流年天干十神
# create new column named man流年天干十神 using shi_shen function, and pass in col man日主 and col ['Year_genzi'][0]
man_df['man流年天干十神'] = man_df.apply(lambda x: shi_shen(x['man日干'], x['Year_genzi'][0]), axis=1)

# 流年地支十神
man_df['man流年地支十神'] = man_df.apply(lambda x: shi_shen(x['man日干'], x['Year_genzi'][1]), axis=1)


#財透干
#create new column named man財透干, if man流年天干十神 is 偏財 or 正財, then True, else False
man_df['man財透干'] = man_df['man流年天干十神'].apply(lambda x: True if x in ['偏財', '正財'] else False)
# man_df['man財透干2'] = man_df['man流年天干十神'].apply(lambda x: True if x in ['偏財', '正財'] else False)
#財得地
#create new column named man財得地, if man流年地支十神 is 偏財 or 正財, then True, else False
man_df['man財得地'] = man_df['man流年地支十神'].apply(lambda x: True if x in ['偏財', '正財'] else False)
# man_df['man財得地2'] = man_df['man流年地支十神'].apply(lambda x: True if x in ['偏財', '正財'] else False)
#大運流年天地合


#流年有傷官

#日干五合
# create new column named man日干五合, if man日干 and 流年天干 is is_wuhe, then True, else False
man_df['man日干五合'] = man_df.apply(lambda row: is_wuhe(row['man日干'], row['Year_genzi'][0]), axis=1)



#流年日柱天地合
#if man日支六合 is True and man日干五合 is true, then True, else False
man_df['man日柱天地合'] = man_df.apply(lambda row: True if row['man日支六合'] and row['man日干五合'] else False, axis=1)

#流年雙體財
man_df['man流年雙體財'] = man_df.apply(lambda row: True if row['man財透干'] and row['man財得地'] else False, axis=1)


# man_df['man日干支關係'] = man_df.apply(lambda row: gan_zhi_relation(row['man日干'], row['man日支']), axis=1)


#create new col named man日支半三合, if man日支 和 流年支 is 半三合, then True, else False
man_df['man日支半三合'] = man_df.apply(lambda row: check_halfsanhe(row['man日支'], row['Year_genzi'][1]), axis=1)


#create new col named man日支半三合, if man日支 和 流年支 is 半三合, then True, else False
man_df['man日支半三會局'] = man_df.apply(lambda row: check_halfsanhuì(row['man日支'], row['Year_genzi'][1]), axis=1)


#日支六合
#if man日支 and 流年支 is_liuhe, then True, else False, and create new column named man日支六合
man_df['man日支暗合'] = man_df.apply(lambda row: check_anhe(row['man日支'], row['Year_genzi'][1]), axis=1)

In [21]:
#日干五沖

man_df['man日干五沖'] = man_df.apply(lambda row: check_clash(row['man日干'], row['Year_genzi'][0]), axis=1)

#半三刑
man_df['man半三刑'] = man_df.apply(lambda row: check_semi_triple_punishment(row['man日干'], row['Year_genzi'][0]), axis=1)

#六害
man_df['man六害'] = man_df.apply(lambda row: check_six_harms(row['man日干'], row['Year_genzi'][0]), axis=1)

In [22]:
# create a new col named man流年天干五神 using man流年天干十神, 
# if  man流年天干五神 == 偏財 or 正財, then 財
# if  man流年天干五神 == 偏官 or 正官, then 官
# if  man流年天干五神 == 偏印 or 正印, then 印
# if  man流年天干五神 == 比肩 or 劫財, then 比劫
# if  man流年天干五神 == 食神 or 傷官, then 食傷
def map_wushen(value):
    """
    Maps the values of 'man流年天干十神' to the corresponding 'man流年天干五神'.

    Arguments:
    value (str): The value of 'man流年天干十神'.

    Returns:
    str: The mapped value of 'man流年天干五神'.
    """
    wushen_mapping = {
        "偏財": "財",
        "正財": "財",
        "七殺": "官",
        "偏官": "官",
        "正官": "官",
        "偏印": "印",
        "正印": "印",
        "比肩": "比劫",
        "劫財": "比劫",
        "食神": "食傷",
        "傷官": "食傷"
    }

    return wushen_mapping.get(value, "")

# Apply the mapping function to create the new column 'man流年天干五神'
man_df['man流年天干五神'] = man_df['man流年天干十神'].apply(map_wushen)
man_df['man流年地支五神'] = man_df['man流年地支十神'].apply(map_wushen)

In [23]:
# create a new col named man流年天干黨派 using man流年天干五神
# if man流年天干五神 == 印 or 比劫, then 同黨
# if man流年天干五神 == 官 or 食傷 or 財 then 異黨

def map_dangpai(value):

    dangpai_mapping = {
        "印": "同黨",
        "比劫": "同黨",
        "官": "異黨",
        "食傷": "異黨",
        "財": "異黨"
    }

    return dangpai_mapping.get(value, "")


man_df['man流年天干黨派'] = man_df['man流年天干五神'].apply(map_dangpai)
man_df['man流年地支黨派'] = man_df['man流年地支五神'].apply(map_dangpai)

In [24]:
#get only 身強身弱 = '強' 
# df_filtered=man_df[man_df['身強身弱'] == '強' ]

In [25]:
man_df

,Male_name,male_birthdate,Year,Event,bazi_man,man年干,man年支,man月干,man月支,man日干,man日支,man時干,man時支,Year_genzi,強弱得令,強弱地支三會,強弱地支三合,強弱得地,強弱得勢,強弱地支半三合,強弱地支半三會,強弱印的數量,身強身弱,man日支同年支,man日支六沖,man日支六合,man流年天干十神,man流年地支十神,man財透干,man財得地,man日干五合,man日柱天地合,man流年雙體財,man日支半三合,man日支半三會局,man日支暗合,man日干五沖,man半三刑,man六害,man流年天干五神,man流年地支五神,man流年天干黨派,man流年地支黨派
0,Ryan Reynolds,1976-02-23,2011,1,"[丙, 辰, 庚, 寅, 乙, 巳, 丙, 子]",丙,辰,庚,寅,乙,巳,丙,子,辛卯,True,False,False,False,False,False,True,0,強,False,False,False,七殺,比肩,False,False,False,False,False,False,False,False,True,False,False,官,比劫,異黨,同黨
1,Colin Jost,1982-06-20,2017,1,"[壬, 戌, 丙, 午, 甲, 戌, 甲, 子]",壬,戌,丙,午,甲,戌,甲,子,丁酉,False,False,False,False,False,False,False,0,弱,False,False,False,傷官,正官,False,False,False,False,False,False,True,False,False,False,False,食傷,官,異黨,異黨
2,Nick Jonas,1992-09-16,2018,1,"[壬, 申, 己, 酉, 乙, 未, 丙, 子]",壬,申,己,酉,乙,未,丙,子,戊戌,False,False,False,False,False,False,False,0,弱,False,False,False,正財,正財,True,True,False,False,True,False,False,False,False,False,False,財,財,異黨,異黨
3,Prince Harry,1984-09-15,2016,1,"[甲, 子, 癸, 酉, 壬, 子, 庚, 子]",甲,子,癸,酉,壬,子,庚,子,丙申,False,False,False,True,True,False,False,0,可能強,False,False,False,偏財,偏印,True,False,False,False,False,True,False,False,True,False,False,財,印,異黨,同黨
4,George Clooney,1961-06-05,2014,1,"[辛, 丑, 癸, 巳, 己, 巳, 甲, 子]",辛,丑,癸,巳,己,巳,甲,子,甲午,False,False,False,False,False,False,False,0,弱,False,False,False,正官,正印,False,False,True,False,False,False,True,False,False,False,False,官,印,異黨,同黨
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,Franchot Tone,1903-05-27,1939,0,"[癸, 卯, 丁, 巳, 乙, 卯, 丙, 子]",癸,卯,丁,巳,乙,卯,丙,子,己卯,False,False,False,True,False,False,False,0,可能強,True,False,False,偏財,比肩,True,False,False,False,False,False,False,False,False,False,False,財,比劫,異黨,同黨
322,Cooke Maroney,1984-06-04,2018,1,"[甲, 子, 己, 巳, 己, 巳, 甲, 子]",甲,子,己,巳,己,巳,甲,子,戊戌,False,False,False,False,True,False,False,0,可能強,False,False,False,劫財,劫財,False,False,False,False,False,False,False,False,False,False,False,比劫,比劫,同黨,同黨
323,Brooklyn Beckham,1999-03-04,2019,1,"[己, 卯, 丙, 寅, 乙, 卯, 丙, 子]",己,卯,丙,寅,乙,卯,丙,子,己亥,True,False,False,True,False,False,True,0,強,False,False,False,偏財,正印,True,False,False,False,False,True,False,False,False,False,False,財,印,異黨,同黨
324,Lily-Rose Depp,1999-05-27,2018,1,"[己, 卯, 己, 巳, 己, 卯, 甲, 子]",己,卯,己,巳,己,卯,甲,子,戊戌,False,False,False,False,True,False,False,0,可能強,False,False,True,劫財,劫財,False,False,False,False,False,False,False,False,False,False,False,比劫,比劫,同黨,同黨
325,Lily-Rose Depp,1999-05-27,2020,0,"[己, 卯, 己, 巳, 己, 卯, 甲, 子]",己,卯,己,巳,己,卯,甲,子,庚子,False,False,False,False,True,False,False,0,可能強,False,False,False,傷官,偏財,False,True,False,False,False,False,False,False,False,False,False,食傷,財,異黨,異黨

In [26]:
df_filtered=man_df

In [27]:
selected_columns

['Male name', 'male_birthdate', 'Year started relationship', 'Year broke up']

In [28]:
#get only the columns we need, Male_name,Event,身強身弱,man日支同年支	man日支六沖	man日支六合	man流年天干十神	man流年地支十神	man財透干	man財得地	man日干五合	man日柱天地合	man流年雙體財	man日支半三合	man日支半三會局	man日支暗合
selected_columns = ['Male_name','Event', '身強身弱', 'man日支同年支', 'man日支六沖', 'man日支六合', 'man流年天干五神', 'man流年天干黨派','man流年地支五神','man流年地支黨派', 'man財透干', 'man財得地', 'man日干五合', 'man日柱天地合', 'man流年雙體財', 'man日支半三合', 'man日支半三會局', 'man日支暗合','man日干五沖','man半三刑','man六害']
selected_df = df_filtered[selected_columns]

In [29]:
# selected_df = man_df.loc[:, ['Male_name','man年干', 'man年支', 'man月干', 'man月支', 'man日干', 'man日支', 'Year_genzi','Event']]

In [30]:
#print first 10 row 
selected_df.head(10)

,Male_name,Event,身強身弱,man日支同年支,man日支六沖,man日支六合,man流年天干五神,man流年天干黨派,man流年地支五神,man流年地支黨派,man財透干,man財得地,man日干五合,man日柱天地合,man流年雙體財,man日支半三合,man日支半三會局,man日支暗合,man日干五沖,man半三刑,man六害
0,Ryan Reynolds,1,強,False,False,False,官,異黨,比劫,同黨,False,False,False,False,False,False,False,False,True,False,False
1,Colin Jost,1,弱,False,False,False,食傷,異黨,官,異黨,False,False,False,False,False,False,True,False,False,False,False
2,Nick Jonas,1,弱,False,False,False,財,異黨,財,異黨,True,True,False,False,True,False,False,False,False,False,False
3,Prince Harry,1,可能強,False,False,False,財,異黨,印,同黨,True,False,False,False,False,True,False,False,True,False,False
4,George Clooney,1,弱,False,False,False,官,異黨,印,同黨,False,False,True,False,False,False,True,False,False,False,False
5,Jay-Z,1,弱,False,False,False,官,異黨,比劫,同黨,False,False,True,False,False,False,True,False,False,False,False
6,John Legend,1,可能強,False,False,False,食傷,異黨,印,同黨,False,False,False,False,False,False,True,False,False,False,False
7,Justin Timberlake,1,強,False,False,False,印,同黨,財,異黨,False,True,False,False,False,False,False,False,False,False,False
8,Ryan Gosling,1,弱,False,False,False,財,異黨,印,同黨,True,False,False,False,False,False,False,False,False,False,False
9,Jesse Plemons,1,強,False,False,False,財,異黨,印,同黨,True,False,False,False,False,False,False,False,True,False,False

In [31]:
selected_df.dtypes

Male_name    object
Event        object
身強身弱         object
man日支同年支     bool
man日支六沖      bool
             ...
man日支半三會局    bool
man日支暗合      bool
man日干五沖      bool
man半三刑       bool
man六害        bool
Length: 21, dtype: object

In [32]:
#show all rows
pd.set_option('display.max_rows', None)

In [63]:
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
import numpy as np

df = combined_final_df

# Define the columns to be encoded
columns_to_encode = df.select_dtypes(include=['object', 'category']).columns.tolist()

# Apply label encoding to the columns
label_encoder = LabelEncoder()
for col in columns_to_encode:
    df[col] = label_encoder.fit_transform(df[col])

# Split the DataFrame into input features (X) and the target variable (y)
X = df.drop(['Male_name', 'Event'], axis=1)
y = df['Event']

# Convert X to numeric data types
X = X.astype(float)
X = X.astype('int')
y = y.astype(float)
y = y.astype('int')

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Calculate class weights
class_counts = np.bincount(y_train)
total_samples = len(y_train)
class_weights = {i: total_samples / count for i, count in enumerate(class_counts)}

# Convert the training and testing data to LightGBM datasets
train_data = lgb.Dataset(X_train, label=y_train, weight=y_train.replace(class_weights))
test_data = lgb.Dataset(X_test, label=y_test)

# Define the parameters for the LightGBM classifier
params = {
    'objective': 'binary',
    'metric': 'binary_logloss',
    'boosting_type': 'gbdt',
    'num_leaves': 3,
    'learning_rate': 0.05,
    'feature_fraction': 0.8,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 0,
    'force_row_wise': True
}

# Train the LightGBM classifier
model = lgb.train(params, train_data, num_boost_round=100)

# Make predictions on the test data
y_pred = model.predict(X_test)
y_pred_binary = [1 if p >= 0.5 else 0 for p in y_pred]

# Evaluate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred_binary)
print('Accuracy:', accuracy)

Accuracy: 0.3611111111111111

In [62]:
selected_df['Event'].value_counts()

1    225
0    90
Name: Event, dtype: int64

In [56]:
#only get 4542 rows where event_type is 1, and get all rows where event_type is 0
marriage_df = selected_df[selected_df['Event'] == 1].sample(90)
divorce_df = selected_df[selected_df['Event'] == 0]

# Concatenate the marriage and divorce DataFrames
combined_final_df = pd.concat([marriage_df, divorce_df])

# Reset the index
combined_final_df.reset_index(drop=True, inplace=True)

# Display the combined DataFrame
combined_final_df

,Male_name,Event,身強身弱,man日支同年支,man日支六沖,man日支六合,man流年天干五神,man流年天干黨派,man流年地支五神,man流年地支黨派,man財透干,man財得地,man日干五合,man日柱天地合,man流年雙體財,man日支半三合,man日支半三會局,man日支暗合,man日干五沖,man半三刑,man六害
0,73,1,0,True,False,False,1,1,2,0,False,False,False,False,False,False,False,False,True,False,False
1,143,1,1,False,True,False,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False
2,13,1,1,False,False,False,4,1,1,1,False,False,False,False,False,False,False,False,False,False,False
3,39,1,0,False,False,False,0,0,4,1,False,False,False,False,False,False,False,False,False,False,False
4,27,1,1,False,False,False,0,0,4,1,False,False,False,False,False,False,False,False,False,False,False
5,174,1,1,True,False,False,4,1,1,1,False,False,False,False,False,False,False,False,False,False,False
6,180,1,1,False,False,False,2,0,3,1,False,True,False,False,False,False,True,False,False,False,False
7,157,1,2,False,False,False,0,0,4,1,False,False,False,False,False,False,False,False,False,False,False
8,56,1,2,False,False,False,4,1,1,1,False,False,False,False,False,True,False,False,False,False,False
9,19,1,2,False,False,False,3,1,0,0,True,False,False,False,False,True,False,False,False,False,False
10,15,1,0,False,False,False,0,0,2,0,False,False,False,False,False,False,False,False,False,False,False
11,25,1,2,False,False,False,0,0,4,1,False,False,False,False,False,False,False,False,False,False,False
12,145,1,1,False,False,False,3,1,0,0,True,False,True,False,False,False,False,True,False,False,False
13,86,1,1,False,False,False,4,1,0,0,False,False,False,False,False,True,False,False,False,False,False
14,179,1,1,False,False,False,0,0,4,1,False,False,False,False,False,False,False,False,False,False,False
15,154,1,1,False,False,False,3,1,0,0,True,False,False,False,False,False,False,False,False,False,False
16,112,1,0,False,False,True,2,0,2,0,False,False,False,False,False,False,False,False,False,False,False
17,178,1,1,False,False,False,1,1,2,0,False,False,False,False,False,False,False,True,False,False,False
18,95,1,0,False,False,False,0,0,4,1,False,False,False,False,False,True,False,False,False,False,False
19,169,1,2,False,False,False,3,1,0,0,True,False,True,False,False,False,False,False,False,False,False
20,71,1,1,False,False,False,3,1,2,0,True,False,False,False,False,True,False,False,True,False,False
21,132,1,0,False,False,False,1,1,2,0,False,False,False,False,False,True,False,False,False,False,False
22,1,1,1,False,True,False,2,0,4,1,False,False,False,False,False,False,False,False,False,False,False
23,28,1,2,False,False,False,2,0,3,1,False,True,False,False,False,False,False,False,False,False,False
24,83,1,1,False,True,False,3,1,0,0,True,False,False,False,False,False,False,False,True,False,False
25,17,1,1,False,False,False,2,0,2,0,False,False,False,False,False,False,False,False,False,False,False
26,157,1,1,False,False,False,4,1,1,1,False,False,False,False,False,False,True,False,False,False,False
27,74,1,1,False,False,False,1,1,2,0,False,False,True,False,False,False,True,False,False,False,False
28,64,1,2,True,False,False,2,0,3,1,False,True,False,False,False,False,False,False,False,False,False
29,135,1,1,True,False,False,2,0,3,1,False,True,False,False,False,False,False,False,False,False,False
30,50,1,0,False,False,False,2,0,1,1,False,False,False,False,False,False,False,False,False,False,False
31,149,1,1,False,False,False,1,1,2,0,False,False,True,False,False,False,False,True,False,False,False
32,54,1,0,False,False,False,4,1,1,1,False,False,False,False,False,False,False,False,False,False,False
33,6,1,1,False,False,False,1,1,2,0,False,False,True,False,False,False,False,False,False,False,False
34,76,1,2,False,True,False,1,1,2,0,False,False,False,False,False,False,False,False,True,False,False
35,121,1,1,False,False,False,2,0,4,1,False,False,False,False,False,False,False,False,False,False,False
36,167,1,0,False,False,False,4,1,4,1,False,False,False,False,False,False,True,False,False,False,False
37,154,1,1,False,False,False,4,1,1,1,False,False,False,False,False,False,False,False,False,False,False
38,47,1,0,False,False,False,4,1,0,0,False,False,False,False,False,False,False,False,False,False,False
39,128,1,0,False,False,False,3,1,1,1,True,False,False,False,False,False,True,False,False,False,False
40,31,1,2,False,True,False,0,0,2,0,False,False,False,False,False,False,False,False,False,False,False
41,173,1,0,True,False,False,3,1,2,0,True,False,False,False,False,False,False,False,False,False,False
42,127,1,1,False,False,False,1,1,0,0,False,False,True,False,False,False,False,False,False,False,False
43,19,1,2,False,True,False,4,1,1,1,False,False,False,False,False,False,False,False,False,False,False
44,78,1,2,False,False,False,3,1,0,0,True,False,False,False,False,False,False,False,True,False,False
45,156,1,0,False,False,True,3,1,2,0,True,False,False,False,False,False,False,False,False,False,False
46,18,1,0,False,False,False,2,0,1,1,False,False,False,False,False,False,False,False,False,False,False
47,74,1,1,False,False,False,1,1,2,0,False,False,True,False,False,False,True,False,False,False,False
48,110,1,2,False,False,False,3,1,2,0,True,False,False,False,False,True,False,False,True,False,False
49,135,1,1,False,False,False,4,1,4,1,False,False,False,False,False,False,True,False,False,False,False
50,7,1,1,True,False,False,0,0,4,1,False,False,False,False,False,False,False,False,False,False,False
51,98,1,1,False,False,False,3,1,1,1,True,False,False,False,False,False,False,False,False,False,False
52,23,1,1,False,False,False,1,1,2,0,False,False,False,False,False,False,False,False,False,False,False
53,102,1,2,False,False,False,1,1,2,0,False,False,False,False,False,False,True,False,True,False,False
54,123,1,1,False,False,False,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False
55,11,1,0,False,False,False,4,1,2,0,False,False,False,False,False,False,False,False,False,False,False
56,159,1,0,False,False,False,1,1,2,0,False,False,False,False,False,True,False,False,False,False,False
57,115,1,0,False,False,True,0,0,4,1,False,False,False,False,False,False,True,False,False,False,False
58,30,1,2,False,False,False,3,1,3,1,True,True,False,False,True,False,False,False,False,False,False
59,136,1,0,False,False,False,0,0,4,1,False,False,False,False,False,False,True,False,False,False,False
60,89,1,0,False,False,True,0,0,1,1,False,False,False,False,False,False,True,False,False,False,False
61,20,1,0,False,False,False,2,0,3,1,False,True,False,False,False,False,False,False,False,False,False
62,22,1,0,True,False,False,1,1,4,1,False,False,False,False,False,False,False,False,False,False,False
63,124,1,0,False,False,True,2,0,1,1,False,False,False,False,False,False,False,False,False,False,False
64,37,1,1,False,False,False,4,1,1,1,False,False,False,False,False,False,False,True,False,False,False
65,65,1,1,False,False,False,4,1,4,1,False,False,False,False,False,False,False,False,False,False,False
66,3,1,1,False,False,True,1,1,2,0,False,False,True,True,False,False,True,False,False,False,False
67,139,1,0,False,False,False,3,1,0,0,True,False,False,False,False,False,False,False,False,False,False
68,172,1,2,False,False,False,1,1,3,1,False,True,False,False,False,True,False,False,True,False,False
69,116,1,2,False,False,True,0,0,4,1,False,False,False,False,False,False,True,False,False,False,False
70,118,1,1,False,True,False,2,0,0,0,False,False,False,False,False,False,False,False,False,False,False
71,20,1,2,False,True,False,4,1,1,1,False,False,False,False,False,False,False,False,False,False,False
72,57,1,1,True,False,False,0,0,4,1,False,False,False,False,False,False,False,False,False,False,False
73,150,1,2,False,False,False,0,0,1,1,False,False,False,False,False,True,False,False,False,False,False
74,90,1,1,False,False,False,2,0,1,1,False,False,False,False,False,True,False,False,False,False,False
75,173,1,1,False,False,True,2,0,1,1,False,False,False,False,False,False,False,False,False,False,False
76,92,1,2,False,False,False,1,1,4,1,False,False,False,False,False,True,False,False,True,False,False
77,178,1,0,False,False,False,3,1,0,0,True,False,True,False,False,False,False,False,False,False,False
78,105,1,0,True,False,False,1,1,2,0,False,False,False,False,False,False,False,False,True,False,False
79,4,1,2,False,False,False,0,0,3,1,False,True,False,False,False,False,False,False,False,False,False
80,24,1,1,False,False,False,2,0,1,1,False,False,False,False,False,True,False,False,False,False,False
81,164,1,0,False,False,False,1,1,3,1,False,True,False,False,False,True,False,False,True,False,False
82,87,1,2,False,False,False,0,0,4,1,False,False,False,False,False,True,False,False,False,False,False
83,162,1,2,False,False,False,1,1,2,0,False,False,False,False,False,False,True,False,False,False,False
84,27,1,1,False,False,False,4,1,0,0,False,False,False,False,False,False,True,False,False,False,False
85,38,1,1,False,False,True,3,1,4,1,True,False,False,False,False,False,False,False,False,False,False
86,3,1,1,False,False,False,4,1,1,1,False,False,False,False,False,True,False,False,False,False,False
87,170,1,2,False,False,True,4,1,2,0,False,False,False,False,False,False,False,False,False,False,False
88,160,1,2,False,False,False,4,1,1,1,False,False,False,False,False,True,False,True,False,False,False
89,117,1,1,False,False,False,4,1,1,1,False,False,False,False,False,False,True,False,False,False,False
90,73,0,0,False,False,False,1,1,0,0,False,False,True,False,False,False,False,False,False,False,False
91,179,0,1,False,True,False,4,1,4,1,False,False,False,False,False,False,False,False,False,False,False
92,165,0,0,False,False,False,1,1,2,0,False,False,False,False,False,True,False,True,False,False,False
93,142,0,1,False,False,False,2,0,3,1,False,True,False,False,False,False,True,False,False,False,False
94,158,0,1,False,True,False,0,0,4,1,False,False,False,False,False,False,False,False,False,False,False
95,50,0,0,False,False,False,1,1,4,1,False,False,False,False,False,False,False,False,False,False,False
96,27,0,1,False,False,True,1,1,2,0,False,False,True,True,False,False,False,False,False,False,False
97,173,0,1,False,False,False,1,1,2,0,False,False,False,False,False,False,False,False,False,False,False
98,108,0,1,False,False,False,1,1,2,0,False,False,False,False,False,True,False,False,False,False,False
99,59,0,0,False,False,False,1,1,1,1,False,False,True,False,False,False,False,False,False,False,False
100,61,0,1,False,False,True,2,0,3,1,False,True,False,False,False,False,False,False,False,False,False
101,53,0,2,False,False,False,2,0,3,1,False,True,False,False,False,False,False,True,False,False,False
102,75,0,2,False,False,False,2,0,2,0,False,False,False,False,False,False,False,False,False,False,False
103,109,0,2,False,False,False,4,1,1,1,False,False,False,False,False,False,False,True,False,False,False
104,150,0,2,True,False,False,1,1,3,1,False,True,False,False,False,False,False,False,False,False,False
105,114,0,0,False,False,False,4,1,2,0,False,False,False,False,False,False,True,False,False,False,False
106,177,0,2,False,False,False,0,0,3,1,False,True,False,False,False,True,False,False,False,False,False
107,9,0,1,True,False,False,1,1,4,1,False,False,False,False,False,False,False,False,True,False,False
108,160,0,2,False,False,False,0,0,4,1,False,False,False,False,False,False,False,False,False,False,False
109,162,0,2,False,False,False,0,0,4,1,False,False,False,False,False,True,False,True,False,False,False
110,143,0,1,False,False,False,0,0,4,1,False,False,False,False,False,False,False,False,False,False,False
111,106,0,0,False,False,False,4,1,4,1,False,False,False,False,False,True,False,False,False,False,False
112,97,0,1,False,False,True,4,1,1,1,False,False,False,False,False,False,False,False,False,False,False
113,64,0,2,False,False,False,4,1,4,1,False,False,False,False,False,False,True,False,False,False,False
114,115,0,0,False,False,False,4,1,4,1,False,False,False,False,False,True,False,False,False,False,False
115,57,0,1,False,False,False,2,0,3,1,False,True,False,False,False,False,False,False,False,False,False
116,73,0,1,False,False,False,3,1,1,1,True,False,False,False,False,False,False,False,False,False,False
117,154,0,1,False,False,False,3,1,0,0,True,False,False,False,False,True,False,False,False,False,False
118,158,0,1,False,True,False,0,0,4,1,False,False,False,False,False,False,False,False,False,False,False
119,27,0,1,False,False,False,0,0,4,1,False,False,False,False,False,False,False,False,False,False,False
120,95,0,0,False,True,False,2,0,3,1,False,True,False,False,False,False,False,False,False,False,False
121,173,0,1,False,False,False,3,1,0,0,True,False,False,False,False,False,True,False,False,False,False
122,50,0,2,False,False,False,1,1,4,1,False,False,False,False,False,False,False,False,False,False,False
123,122,0,1,False,False,False,1,1,0,0,False,False,True,False,False,False,True,False,False,False,False
124,2,0,1,False,False,False,0,0,2,0,False,False,False,False,False,True,False,False,False,False,False
125,111,0,1,False,False,False,4,1,1,1,False,False,False,False,False,False,False,False,False,False,False
126,135,0,1,False,False,False,4,1,1,1,False,False,False,False,False,False,False,False,False,False,False
127,19,0,2,False,False,True,3,1,3,1,True,True,False,False,True,False,False,False,False,False,False
128,12,0,0,False,False,False,1,1,0,0,False,False,True,False,False,False,True,False,False,False,False
129,67,0,0,False,False,True,1,1,1,1,False,False,True,True,False,False,False,False,False,False,False
130,138,0,0,False,False,False,2,0,3,1,False,True,False,False,False,False,True,False,False,False,False
131,10,0,1,False,False,False,1,1,2,0,False,False,False,False,False,False,False,False,False,False,False
132,19,0,2,False,False,True,3,1,3,1,True,True,False,False,True,False,False,False,False,False,False
133,135,0,1,False,False,False,4,1,4,1,False,False,False,False,False,False,True,False,False,False,False
134,121,0,1,False,False,False,3,1,0,0,True,False,True,False,False,False,False,False,False,False,False
135,66,0,2,False,False,False,3,1,1,1,True,False,False,False,False,False,False,False,False,False,False
136,112,0,0,False,False,False,4,1,3,1,False,True,False,False,False,False,False,False,False,False,False
137,95,0,0,False,False,True,4,1,4,1,False,False,False,False,False,False,False,False,False,False,False
138,124,0,1,False,False,False,3,1,0,0,True,False,False,False,False,False,False,False,False,False,False
139,136,0,0,False,False,False,3,1,1,1,True,False,False,False,False,False,False,True,False,False,False
140,86,0,1,False,True,False,3,1,1,1,True,False,False,False,False,False,False,False,True,False,False
141,28,0,2,False,False,False,2,0,3,1,False,True,False,False,False,True,False,False,False,False,False
142,145,0,1,False,True,False,1,1,0,0,False,False,False,False,False,False,False,False,True,False,False
143,128,0,0,True,False,False,2,0,1,1,False,False,False,False,False,False,False,False,False,False,False
144,107,0,1,False,False,False,1,1,2,0,False,False,True,False,False,False,False,False,False,False,False
145,36,0,1,False,False,False,2,0,3,1,False,True,False,False,False,False,False,True,False,False,False
146,71,0,1,False,False,False,0,0,4,1,False,False,False,False,False,False,True,False,False,False,False
147,129,0,2,False,False,False,3,1,2,0,True,False,False,False,False,True,False,False,False,False,False
148,72,0,0,False,False,False,4,1,2,0,False,False,False,False,False,False,False,False,False,False,False
149,49,0,1,False,False,False,1,1,3,1,False,True,True,False,False,False,False,False,False,False,False
150,101,0,2,False,True,False,3,1,4,1,True,False,False,False,False,False,False,False,False,False,False
151,18,0,0,False,False,False,4,1,1,1,False,False,False,False,False,False,False,False,False,False,False
152,16,0,2,False,False,False,1,1,4,1,False,False,False,False,False,False,False,False,True,False,False
153,90,0,1,False,False,False,4,1,0,0,False,False,False,False,False,False,False,True,False,False,False
154,127,0,1,False,False,False,0,0,4,1,False,False,False,False,False,True,False,False,False,False,False
155,124,0,0,False,False,False,1,1,2,0,False,False,False,False,False,False,True,False,True,False,False
156,14,0,1,False,False,False,2,0,3,1,False,True,False,False,False,False,False,False,False,False,False
157,31,0,2,False,False,False,2,0,3,1,False,True,False,False,False,False,False,False,False,False,False
158,11,0,0,False,False,False,2,0,2,0,False,False,False,False,False,True,False,False,False,False,False
159,142,0,1,False,False,False,4,1,1,1,False,False,False,False,False,False,True,False,False,False,False
160,110,0,2,False,False,False,1,1,2,0,False,False,True,False,False,False,False,False,False,False,False
161,4,0,2,False,False,True,2,0,1,1,False,False,False,False,False,False,False,False,False,False,False
162,164,0,0,False,False,False,1,1,4,1,False,False,False,False,False,False,False,False,True,False,False
163,167,0,0,False,False,False,4,1,4,1,False,False,False,False,False,False,False,False,False,False,False
164,80,0,0,False,False,False,2,0,3,1,False,True,False,False,False,False,False,False,False,False,False
165,173,0,0,False,False,False,0,0,4,1,False,False,False,False,False,True,False,False,False,False,False
166,128,0,0,False,False,False,2,0,4,1,False,False,False,False,False,False,False,False,False,False,False
167,172,0,2,True,False,False,4,1,1,1,False,False,False,False,False,False,False,False,False,False,False
168,5,0,1,True,False,False,3,1,0,0,True,False,False,False,False,False,False,False,False,False,False
169,130,0,1,False,False,False,1,1,2,0,False,False,False,False,False,False,False,False,False,False,False
170,117,0,1,False,False,False,4,1,2,0,False,False,False,False,False,False,False,False,False,False,False
171,152,0,0,False,True,False,0,0,4,1,False,False,False,False,False,False,False,False,False,False,False
172,48,0,2,False,False,False,1,1,3,1,False,True,False,False,False,True,False,False,False,False,False
173,42,0,0,False,False,False,0,0,2,0,False,False,False,False,False,False,False,False,False,False,False
174,85,0,1,False,False,False,3,1,0,0,True,False,False,False,False,True,False,False,True,False,False
175,132,0,0,False,False,False,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False
176,149,0,1,False,False,True,4,1,0,0,False,False,False,False,False,False,False,False,False,False,False
177,125,0,0,False,False,False,2,0,4,1,False,False,False,False,False,False,False,False,False,False,False
178,51,0,0,True,False,False,3,1,2,0,True,False,False,False,False,False,False,False,False,False,False
179,112,0,0,False,False,False,4,1,3,1,False,True,False,False,False,False,False,False,False,False,False

In [57]:
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
df=combined_final_df
# Define the columns to be encoded
# columns_to_encode = ['身強身弱', 'man流年天干五神', 'man流年地支五神']
columns_to_encode = df.select_dtypes(include=['object', 'category']).columns.tolist()
# Apply label encoding to the columns
label_encoder = LabelEncoder()
for col in columns_to_encode:
    df[col] = label_encoder.fit_transform(df[col])
    
# df['身強身弱'] = df['身強身弱'].astype('category')
# df['man流年天干五神'] = df['man流年天干五神'].astype('category')
# df['man流年地支五神'] = df['man流年地支五神'].astype('category')

# Split the DataFrame into input features (X) and the target variable (y)
# X = df.drop(['Male_name', 'Event','身強身弱','man流年天干五神','man流年地支五神'], axis=1)
# X = df.drop(['Male_name', 'Event','身強身弱'], axis=1)
X = df.drop(['Male_name', 'Event'], axis=1)
y = df['Event']

# Convert X to numeric data types
X = X.astype(float)
X = X.astype('int')
y = y.astype(float)
y = y.astype('int')
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Convert the training and testing data to LightGBM datasets
train_data = lgb.Dataset(X_train, label=y_train)
test_data = lgb.Dataset(X_test, label=y_test)

# Define the parameters for the LightGBM classifier
params = {
    'objective': 'binary',
    'metric': 'binary_logloss',
    'boosting_type': 'gbdt',
    'num_leaves': 3,
    # 'num_leaves': 31,
    'learning_rate': 0.05,
    'feature_fraction': 0.8,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 0,
    'force_row_wise': True
}


# lgb.set_config(force_row_wise=True)
# Train the LightGBM classifier
model = lgb.train(params, train_data, num_boost_round=100)

# Make predictions on the test data
y_pred = model.predict(X_test)
y_pred_binary = [1 if p >= 0.5 else 0 for p in y_pred]

# Evaluate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred_binary)
print('Accuracy:', accuracy)

Accuracy: 0.3611111111111111

In [42]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

# Split the DataFrame into input features (X) and the target variable (y)
X = df.drop(['Male_name', 'Event'], axis=1)
y = df['Event']
X = X.astype(float)
X = X.astype('int')
y = y.astype(int)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Random Forest classifier
rf_model = RandomForestClassifier(random_state=42)

# Define the parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [100, 200, 300],  # Try different numbers of trees
    'max_depth': [None, 5, 10],       # Try different maximum depths
    'min_samples_split': [2, 5, 10]   # Try different minimum samples for splitting
}

# Perform grid search to find the best hyperparameters
grid_search = GridSearchCV(rf_model, param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Get the best model with the optimal hyperparameters
best_rf_model = grid_search.best_estimator_

# Make predictions on the test data
y_pred = best_rf_model.predict(X_test)

# Evaluate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

Accuracy: 0.4444444444444444