In [1]:
# C:\Users\TOSHIBA\Documents\Github\FateAi\DATAS\top_100_richest.csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

rich = pd.read_csv('C:\\Users\\TOSHIBA\\Documents\\Github\\FateAi\\DATAS\\top_100_richest.csv')
rich.head()

,rank,name,net_worth,bday,age,nationality
0,1,Elon Musk,$240 Billion,28-Jun-71,51.0,South Africa
1,2,Jeff Bezos,$150 Billion,12-Jan-64,58.0,United States of America
2,3,Gautam Adani,$138 Billion,24-Jun-62,60.0,India
3,4,Bernard Arnault,$135 Billion,5-Mar-49,73.0,France
4,5,Bill Gates,$118 Billion,28-Oct-55,66.0,United States of America

In [3]:
#convert bday to datetime
rich['Birthday'] = pd.to_datetime(rich['bday'])
rich.head()

,rank,name,net_worth,bday,age,nationality,Birthday
0,1,Elon Musk,$240 Billion,28-Jun-71,51.0,South Africa,2071-06-28
1,2,Jeff Bezos,$150 Billion,12-Jan-64,58.0,United States of America,2064-01-12
2,3,Gautam Adani,$138 Billion,24-Jun-62,60.0,India,2062-06-24
3,4,Bernard Arnault,$135 Billion,5-Mar-49,73.0,France,2049-03-05
4,5,Bill Gates,$118 Billion,28-Oct-55,66.0,United States of America,2055-10-28

In [4]:
import sys
sys.path.append(r"C:\Users\TOSHIBA\Documents\Github\FateAi\crystal-bazi")
# import main
import metaphysic
def getBazi(year,month,day,hour):
    ba=metaphysic.bazi(year,month,day,hour)
    ba=ba.split("-")
    bazi=[]
    for i in ba:
        # print(i.split())
        bazi.append(i[0])
        bazi.append(i[1])
    return bazi
bazi=getBazi(1996,9,17,3)
bazi

changed sth
输入:[1996-9-17]; 输出:[1996-8-5]; 天干地支:[丙子-丁酉-丁巳]; 生肖:[鼠]

['丙', '子', '丁', '酉', '丁', '巳', '壬', '寅']

In [5]:
rich['bazi_man'] = rich['Birthday'].apply(lambda x: getBazi(int(x.strftime('%Y')), int(x.strftime('%m')), int(x.strftime('%d')), 0) if not pd.isnull(x) else None)
rich

changed sth
输入:[2071-6-28]; 输出:[2071-6-1]; 天干地支:[辛卯-甲午-己巳]; 生肖:[兔]
changed sth
输入:[2064-1-12]; 输出:[2063-11-24]; 天干地支:[癸未-乙丑-乙巳]; 生肖:[羊]
changed sth
输入:[2062-6-24]; 输出:[2062-5-18]; 天干地支:[壬午-丙午-戊寅]; 生肖:[馬]
changed sth
输入:[2049-3-5]; 输出:[2049-2-2]; 天干地支:[己巳-丁卯-己卯]; 生肖:[蛇]
changed sth
输入:[2055-10-28]; 输出:[2055-9-9]; 天干地支:[乙亥-丙戌-丁未]; 生肖:[豬]
changed sth
输入:[2030-8-30]; 输出:[2030-8-2]; 天干地支:[庚戌-甲申-丁酉]; 生肖:[狗]
changed sth
输入:[1973-3-26]; 输出:[1973-2-22]; 天干地支:[癸丑-乙卯-辛酉]; 生肖:[牛]
changed sth
输入:[1973-8-21]; 输出:[1973-7-23]; 天干地支:[癸丑-庚申-己丑]; 生肖:[牛]
changed sth
输入:[2056-3-24]; 输出:[2056-2-9]; 天干地支:[丙子-辛卯-乙亥]; 生肖:[鼠]
changed sth
输入:[2044-8-17]; 输出:[2044-7-24]; 天干地支:[甲子-壬申-戊戌]; 生肖:[鼠]
changed sth
输入:[2057-4-19]; 输出:[2057-3-16]; 天干地支:[丁丑-甲辰-丙午]; 生肖:[牛]
changed sth
输入:[2040-1-28]; 输出:[2039-12-15]; 天干地支:[己未-丁丑-乙卯]; 生肖:[羊]
changed sth
输入:[2052-10-7]; 输出:[2052-8-15]; 天干地支:[壬申-庚戌-辛未]; 生肖:[猴]
changed sth
输入:[2053-7-10]; 输出:[2053-5-25]; 天干地支:[癸酉-己未-丁未]; 生肖:[雞]
changed sth
输入:[2036-3-28]; 输出:[2036-3-1]; 天干地支:[丙辰-辛卯-甲午]; 生肖:[龍]
changed sth
输入:[2042-2-14]; 输出:[2042-1-24]; 天干地支:[壬戌-壬寅-癸未]; 生肖:[狗]
changed sth
输入:[1984-5-14]; 输出:[1984-4-14]; 天干地支:[甲子-己巳-戊申]; 生肖:[鼠]
changed sth
输入:[2044-10-28]; 输出:[2044-9-8]; 天干地支:[甲子-甲戌-庚戌]; 生肖:[鼠]
changed sth
输入:[2048-6-7]; 输出:[2048-4-26]; 天干地支:[戊辰-戊午-戊申]; 生肖:[龍]
changed sth
输入:[2049-10-7]; 输出:[2049-9-11]; 天干地支:[己巳-癸酉-乙卯]; 生肖:[蛇]
changed sth
输入:[2062-4-12]; 输出:[2062-3-3]; 天干地支:[壬午-甲辰-乙丑]; 生肖:[馬]
changed sth
输入:[2035-11-1]; 输出:[2035-10-2]; 天干地支:[乙卯-丙戌-丙寅]; 生肖:[兔]
changed sth
输入:[2065-2-23]; 输出:[2065-1-19]; 天干地支:[乙酉-戊寅-癸巳]; 生肖:[雞]
changed sth
输入:[2036-8-21]; 输出:[2036-6-30]; 天干地支:[丙辰-丙申-庚申]; 生肖:[龍]
changed sth
输入:[2057-6-12]; 输出:[2057-5-11]; 天干地支:[丁丑-丙午-庚子]; 生肖:[牛]
changed sth
输入:[2071-10-29]; 输出:[2071-9-7]; 天干地支:[辛卯-戊戌-壬申]; 生肖:[兔]
changed sth
输入:[2048-9-28]; 输出:[2048-8-21]; 天干地支:[戊辰-辛酉-辛丑]; 生肖:[龍]
changed sth
输入:[2051-4-17]; 输出:[2051-3-7]; 天干地支:[辛未-壬辰-壬申]; 生肖:[羊]
changed sth
输入:[1983-4-1]; 输出:[1983-2-18]; 天干地支:[癸亥-乙卯-己未]; 生肖:[豬]
changed sth
输入:[2049-2-7]; 输出:[2049-1-6]; 天干地支:[己巳-丙寅-癸丑]; 生肖:[蛇]
changed sth
输入:[2035-10-15]; 输出:[2035-9-15]; 天干地支:[乙卯-丙戌-己酉]; 生肖:[兔]
changed sth
输入:[2039-10-10]; 输出:[2039-8-23]; 天干地支:[己未-甲戌-乙丑]; 生肖:[羊]
changed sth
输入:[2038-2-24]; 输出:[2038-1-21]; 天干地支:[戊午-甲寅-壬申]; 生肖:[馬]
changed sth
输入:[2061-1-3]; 输出:[2060-12-12]; 天干地支:[庚辰-戊子-辛巳]; 生肖:[龍]
changed sth
输入:[2047-2-14]; 输出:[2047-1-20]; 天干地支:[丁卯-壬寅-己酉]; 生肖:[兔]
changed sth
输入:[2064-10-15]; 输出:[2064-9-6]; 天干地支:[甲申-甲戌-壬午]; 生肖:[猴]
changed sth
输入:[2045-10-10]; 输出:[2045-9-1]; 天干地支:[乙丑-丙戌-丁酉]; 生肖:[牛]
changed sth
输入:[1980-1-1]; 输出:[1979-11-14]; 天干地支:[己未-丙子-癸酉]; 生肖:[羊]
changed sth
输入:[2028-1-29]; 输出:[2027-1-4]; 天干地支:[丁未-癸丑-癸丑]; 生肖:[羊]
changed sth
输入:[2057-6-14]; 输出:[2057-5-13]; 天干地支:[丁丑-丙午-壬寅]; 生肖:[牛]
changed sth
输入:[2028-7-29]; 输出:[2028-6-8]; 天干地支:[戊申-己未-乙卯]; 生肖:[猴]
changed sth
输入:[2054-2-9]; 输出:[2054-1-2]; 天干地支:[甲戌-丙寅-辛巳]; 生肖:[狗]
changed sth
输入:[2070-11-20]; 输出:[2070-10-18]; 天干地支:[庚寅-丁亥-己丑]; 生肖:[虎]
changed sth
输入:[2057-8-11]; 输出:[2057-7-12]; 天干地支:[丁丑-戊申-庚子]; 生肖:[牛]
changed sth
输入:[2046-7-15]; 输出:[2046-6-12]; 天干地支:[丙寅-乙未-乙亥]; 生肖:[虎]
changed sth
输入:[2052-7-28]; 输出:[2052-7-3]; 天干地支:[壬申-丁未-庚申]; 生肖:[猴]
changed sth
输入:[2064-9-21]; 输出:[2064-8-11]; 天干地支:[甲申-癸酉-戊午]; 生肖:[猴]
changed sth
输入:[2068-10-15]; 输出:[2068-9-20]; 天干地支:[戊子-壬戌-癸卯]; 生肖:[鼠]
changed sth
输入:[2061-12-19]; 输出:[2061-11-8]; 天干地支:[辛巳-庚子-辛未]; 生肖:[蛇]
changed sth
输入:[2042-10-5]; 输出:[2042-8-22]; 天干地支:[壬戌-己酉-丙子]; 生肖:[狗]
changed sth
输入:[2039-9-24]; 输出:[2039-8-7]; 天干地支:[己未-癸酉-己酉]; 生肖:[羊]
changed sth
输入:[2071-10-1]; 输出:[2071-8-8]; 天干地支:[辛卯-丁酉-甲辰]; 生肖:[兔]
changed sth
输入:[2045-7-14]; 输出:[2045-6-1]; 天干地支:[乙丑-癸未-己巳]; 生肖:[牛]
changed sth
输入:[2047-10-4]; 输出:[2047-8-15]; 天干地支:[丁卯-己酉-辛丑]; 生肖:[兔]
changed sth
输入:[2038-9-1]; 输出:[2038-8-3]; 天干地支:[戊午-庚申-辛巳]; 生肖:[馬]
changed sth
输入:[2070-2-20]; 输出:[2070-1-10]; 天干地支:[庚寅-戊寅-丙辰]; 生肖:[虎]
changed sth
输入:[2036-2-16]; 输出:[2036-1-20]; 天干地支:[丙辰-庚寅-癸丑]; 生肖:[龍]
changed sth
输入:[2045-6-10]; 输出:[2045-4-25]; 天干地支:[乙丑-壬午-乙未]; 生肖:[牛]
changed sth
输入:[2067-6-21]; 输出:[2067-5-10]; 天干地支:[丁亥-丙午-辛丑]; 生肖:[豬]
changed sth
输入:[2031-8-16]; 输出:[2031-6-29]; 天干地支:[辛亥-丙申-戊子]; 生肖:[豬]
changed sth
输入:[2039-8-26]; 输出:[2039-7-7]; 天干地支:[己未-壬申-庚辰]; 生肖:[羊]
changed sth
输入:[2055-4-27]; 输出:[2055-4-1]; 天干地支:[乙亥-庚辰-癸卯]; 生肖:[豬]
changed sth
输入:[1975-4-5]; 输出:[1975-2-24]; 天干地支:[乙卯-庚辰-辛巳]; 生肖:[兔]
changed sth
输入:[2038-4-25]; 输出:[2038-3-21]; 天干地支:[戊午-丙辰-壬申]; 生肖:[馬]
changed sth
输入:[2047-5-2]; 输出:[2047-4-8]; 天干地支:[丁卯-甲辰-丙寅]; 生肖:[兔]
changed sth
输入:[2057-4-10]; 输出:[2057-3-7]; 天干地支:[丁丑-甲辰-丁酉]; 生肖:[牛]
changed sth
输入:[2033-3-19]; 输出:[2033-2-19]; 天干地支:[癸丑-乙卯-己巳]; 生肖:[牛]
changed sth
输入:[2072-3-8]; 输出:[2072-1-19]; 天干地支:[壬辰-癸卯-癸未]; 生肖:[龍]
changed sth
输入:[2031-8-29]; 输出:[2031-7-12]; 天干地支:[辛亥-丙申-辛丑]; 生肖:[豬]
changed sth
输入:[2035-12-31]; 输出:[2035-12-3]; 天干地支:[乙卯-戊子-丙寅]; 生肖:[兔]
changed sth
输入:[2065-9-26]; 输出:[2065-8-26]; 天干地支:[乙酉-乙酉-戊辰]; 生肖:[雞]
changed sth
输入:[2040-1-22]; 输出:[2039-12-9]; 天干地支:[己未-丁丑-己酉]; 生肖:[羊]
changed sth
输入:[2045-11-18]; 输出:[2045-10-10]; 天干地支:[乙丑-丁亥-丙子]; 生肖:[牛]
changed sth
输入:[2031-3-11]; 输出:[2031-2-19]; 天干地支:[辛亥-辛卯-庚戌]; 生肖:[豬]
changed sth
输入:[2062-1-17]; 输出:[2061-12-7]; 天干地支:[辛巳-辛丑-庚子]; 生肖:[蛇]
changed sth
输入:[2055-8-11]; 输出:[2055-6-19]; 天干地支:[乙亥-甲申-己丑]; 生肖:[豬]
changed sth
输入:[2029-6-1]; 输出:[2029-4-20]; 天干地支:[己酉-己巳-壬戌]; 生肖:[雞]
changed sth
输入:[2062-4-28]; 输出:[2062-3-19]; 天干地支:[壬午-甲辰-辛巳]; 生肖:[馬]
changed sth
输入:[1982-3-19]; 输出:[1982-2-24]; 天干地支:[壬戌-癸卯-辛丑]; 生肖:[狗]
changed sth
输入:[2056-5-7]; 输出:[2056-3-23]; 天干地支:[丙子-癸巳-己未]; 生肖:[鼠]
changed sth
输入:[2052-10-18]; 输出:[2052-8-26]; 天干地支:[壬申-庚戌-壬午]; 生肖:[猴]
changed sth
输入:[2063-11-6]; 输出:[2063-9-16]; 天干地支:[癸未-壬戌-戊戌]; 生肖:[羊]
changed sth
输入:[2050-9-2]; 输出:[2050-7-17]; 天干地支:[庚午-甲申-乙酉]; 生肖:[馬]
changed sth
输入:[2048-1-25]; 输出:[2047-12-11]; 天干地支:[丁卯-癸丑-甲午]; 生肖:[兔]
changed sth
输入:[2053-9-9]; 输出:[2053-7-27]; 天干地支:[癸酉-辛酉-戊申]; 生肖:[雞]
changed sth
输入:[2025-4-4]; 输出:[2025-3-7]; 天干地支:[乙巳-庚辰-癸卯]; 生肖:[蛇]
changed sth
输入:[1984-10-10]; 输出:[1984-9-16]; 天干地支:[甲子-甲戌-丁丑]; 生肖:[鼠]
changed sth
输入:[2032-5-11]; 输出:[2032-4-3]; 天干地支:[壬子-乙巳-丁巳]; 生肖:[鼠]
changed sth
输入:[2044-9-30]; 输出:[2044-8-10]; 天干地支:[甲子-癸酉-壬午]; 生肖:[鼠]
changed sth
输入:[2055-3-7]; 输出:[2055-2-10]; 天干地支:[乙亥-己卯-壬子]; 生肖:[豬]
changed sth
输入:[2045-12-11]; 输出:[2045-11-4]; 天干地支:[乙丑-戊子-己亥]; 生肖:[牛]
changed sth
输入:[2057-4-14]; 输出:[2057-3-11]; 天干地支:[丁丑-甲辰-辛丑]; 生肖:[牛]
changed sth
输入:[2056-6-11]; 输出:[2056-4-28]; 天干地支:[丙子-甲午-甲午]; 生肖:[鼠]
changed sth
输入:[2066-5-9]; 输出:[2066-4-16]; 天干地支:[丙戌-癸巳-癸丑]; 生肖:[狗]

,rank,name,net_worth,bday,age,nationality,Birthday,bazi_man
0,1,Elon Musk,$240 Billion,28-Jun-71,51.0,South Africa,2071-06-28,"[辛, 卯, 甲, 午, 己, 巳, 甲, 子]"
1,2,Jeff Bezos,$150 Billion,12-Jan-64,58.0,United States of America,2064-01-12,"[癸, 未, 乙, 丑, 乙, 巳, 丙, 子]"
2,3,Gautam Adani,$138 Billion,24-Jun-62,60.0,India,2062-06-24,"[壬, 午, 丙, 午, 戊, 寅, 壬, 子]"
3,4,Bernard Arnault,$135 Billion,5-Mar-49,73.0,France,2049-03-05,"[己, 巳, 丁, 卯, 己, 卯, 甲, 子]"
4,5,Bill Gates,$118 Billion,28-Oct-55,66.0,United States of America,2055-10-28,"[乙, 亥, 丙, 戌, 丁, 未, 庚, 子]"
...,...,...,...,...,...,...,...,...
95,96,Prince Al Waleed Bin Talal Alsaud,$17 Billion,7-Mar-55,67.0,Saudi Arabia,2055-03-07,"[乙, 亥, 己, 卯, 壬, 子, 庚, 子]"
96,97,Harold Hamm,$17 Billion,11-Dec-45,76.0,United States of America,2045-12-11,"[乙, 丑, 戊, 子, 己, 亥, 甲, 子]"
97,98,Viktor Vekselberg,$17 Billion,14-Apr-57,65.0,Russia,2057-04-14,"[丁, 丑, 甲, 辰, 辛, 丑, 戊, 子]"
98,99,Steven Cohen,$16 Billion,11-Jun-56,66.0,United States of America,2056-06-11,"[丙, 子, 甲, 午, 甲, 午, 甲, 子]"
99,100,Stefan Quandt,$16 Billion,9-May-66,56.0,Germany,2066-05-09,"[丙, 戌, 癸, 巳, 癸, 丑, 壬, 子]"

In [13]:
#print all rows
pd.set_option('display.max_rows', None)
rich

,rank,name,net_worth,bday,age,nationality,Birthday,bazi_man,man年干,man年支,man月干,man月支,man日干,man日支,man時干,man時支
0,1,Elon Musk,$240 Billion,28-Jun-71,51.0,South Africa,2071-06-28,"[辛, 卯, 甲, 午, 己, 巳, 甲, 子]",辛,卯,甲,午,己,巳,甲,子
1,2,Jeff Bezos,$150 Billion,12-Jan-64,58.0,United States of America,2064-01-12,"[癸, 未, 乙, 丑, 乙, 巳, 丙, 子]",癸,未,乙,丑,乙,巳,丙,子
2,3,Gautam Adani,$138 Billion,24-Jun-62,60.0,India,2062-06-24,"[壬, 午, 丙, 午, 戊, 寅, 壬, 子]",壬,午,丙,午,戊,寅,壬,子
3,4,Bernard Arnault,$135 Billion,5-Mar-49,73.0,France,2049-03-05,"[己, 巳, 丁, 卯, 己, 卯, 甲, 子]",己,巳,丁,卯,己,卯,甲,子
4,5,Bill Gates,$118 Billion,28-Oct-55,66.0,United States of America,2055-10-28,"[乙, 亥, 丙, 戌, 丁, 未, 庚, 子]",乙,亥,丙,戌,丁,未,庚,子
5,6,Warren Buffett,$101 Billion,30-Aug-30,92.0,United States of America,2030-08-30,"[庚, 戌, 甲, 申, 丁, 酉, 庚, 子]",庚,戌,甲,申,丁,酉,庚,子
6,7,Larry Page,$100 Billion,26-Mar-73,49.0,United States of America,1973-03-26,"[癸, 丑, 乙, 卯, 辛, 酉, 戊, 子]",癸,丑,乙,卯,辛,酉,戊,子
7,8,Sergey Brin,$96 Billion,21-Aug-73,48.0,United States of America,1973-08-21,"[癸, 丑, 庚, 申, 己, 丑, 甲, 子]",癸,丑,庚,申,己,丑,甲,子
8,9,Steve Ballmer,$94 Billion,24-Mar-56,66.0,United States of America,2056-03-24,"[丙, 子, 辛, 卯, 乙, 亥, 丙, 子]",丙,子,辛,卯,乙,亥,丙,子
9,10,Larry Ellison,$93 Billion,17-Aug-44,78.0,United States of America,2044-08-17,"[甲, 子, 壬, 申, 戊, 戌, 壬, 子]",甲,子,壬,申,戊,戌,壬,子
10,11,Alain & Gerard Wertheimer,$90 Billion,NaN,NaN,France,NaT,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,Mukesh Ambani,$89 Billion,19-Apr-57,65.0,India,2057-04-19,"[丁, 丑, 甲, 辰, 丙, 午, 戊, 子]",丁,丑,甲,辰,丙,午,戊,子
12,13,Carlos Slim Helu,$72 Billion,28-Jan-40,82.0,Mexico,2040-01-28,"[己, 未, 丁, 丑, 乙, 卯, 丙, 子]",己,未,丁,丑,乙,卯,丙,子
13,14,Vladimir Putin,$70 Billion,7-Oct-52,69.0,Russia,2052-10-07,"[壬, 申, 庚, 戌, 辛, 未, 戊, 子]",壬,申,庚,戌,辛,未,戊,子
14,15,Françoise Bettencourt-Meyers,$70 Billion,10-Jul-53,69.0,France,2053-07-10,"[癸, 酉, 己, 未, 丁, 未, 庚, 子]",癸,酉,己,未,丁,未,庚,子
15,16,Amancio Ortega Gaona,$70 Billion,28-Mar-36,86.0,Spain,2036-03-28,"[丙, 辰, 辛, 卯, 甲, 午, 甲, 子]",丙,辰,辛,卯,甲,午,甲,子
16,17,Michael Bloomberg,$70 Billion,14-Feb-42,80.0,United States of America,2042-02-14,"[壬, 戌, 壬, 寅, 癸, 未, 壬, 子]",壬,戌,壬,寅,癸,未,壬,子
17,18,Mark Zuckerberg,$70 Billion,14-May-84,38.0,United States of America,1984-05-14,"[甲, 子, 己, 巳, 戊, 申, 壬, 子]",甲,子,己,巳,戊,申,壬,子
18,19,Rob Walton,$68 Billion,28-Oct-44,77.0,United States of America,2044-10-28,"[甲, 子, 甲, 戌, 庚, 戌, 丙, 子]",甲,子,甲,戌,庚,戌,丙,子
19,20,Jim Walton,$68 Billion,7-Jun-48,74.0,United States of America,2048-06-07,"[戊, 辰, 戊, 午, 戊, 申, 壬, 子]",戊,辰,戊,午,戊,申,壬,子
20,21,Zhong Shanshan,$68 Billion,NaN,NaN,China,NaT,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,Alice Walton,$66 Billion,7-Oct-49,72.0,United States of America,2049-10-07,"[己, 巳, 癸, 酉, 乙, 卯, 丙, 子]",己,巳,癸,酉,乙,卯,丙,子
22,23,Julia Flesher Koch,$62 Billion,12-Apr-62,60.0,United States of America,2062-04-12,"[壬, 午, 甲, 辰, 乙, 丑, 丙, 子]",壬,午,甲,辰,乙,丑,丙,子
23,24,Charles Koch,$60 Billion,1-Nov-35,86.0,United States of America,2035-11-01,"[乙, 卯, 丙, 戌, 丙, 寅, 戊, 子]",乙,卯,丙,戌,丙,寅,戊,子
24,25,Michael Dell,$52 Billion,23-Feb-65,57.0,United States of America,2065-02-23,"[乙, 酉, 戊, 寅, 癸, 巳, 壬, 子]",乙,酉,戊,寅,癸,巳,壬,子
25,26,Francois Pinault,$50 Billion,21-Aug-36,86.0,France,2036-08-21,"[丙, 辰, 丙, 申, 庚, 申, 丙, 子]",丙,辰,丙,申,庚,申,丙,子
26,27,David Thomson,$50 Billion,12-Jun-57,65.0,Canada,2057-06-12,"[丁, 丑, 丙, 午, 庚, 子, 丙, 子]",丁,丑,丙,午,庚,子,丙,子
27,28,Ma Huateng,$48 Billion,29-Oct-71,50.0,China,2071-10-29,"[辛, 卯, 戊, 戌, 壬, 申, 庚, 子]",辛,卯,戊,戌,壬,申,庚,子
28,29,Alain Wertheimer,$45 Billion,28-Sep-48,73.0,France,2048-09-28,"[戊, 辰, 辛, 酉, 辛, 丑, 戊, 子]",戊,辰,辛,酉,辛,丑,戊,子
29,30,Gerard Wertheimer,$45 Billion,17-Apr-51,71.0,French,2051-04-17,"[辛, 未, 壬, 辰, 壬, 申, 庚, 子]",辛,未,壬,辰,壬,申,庚,子
30,31,Zhang Yiming,$44 Billion,1-Apr-83,39.0,China,1983-04-01,"[癸, 亥, 乙, 卯, 己, 未, 甲, 子]",癸,亥,乙,卯,己,未,甲,子
31,32,Tadashi Yanai,$42 Billion,7-Feb-49,73.0,Japan,2049-02-07,"[己, 巳, 丙, 寅, 癸, 丑, 壬, 子]",己,巳,丙,寅,癸,丑,壬,子
32,33,John Mars,$42 Billion,15-Oct-35,86.0,United States of America,2035-10-15,"[乙, 卯, 丙, 戌, 己, 酉, 甲, 子]",乙,卯,丙,戌,己,酉,甲,子
33,34,Jacqueline Mars,$42 Billion,10-Oct-39,82.0,United States of America,2039-10-10,"[己, 未, 甲, 戌, 乙, 丑, 丙, 子]",己,未,甲,戌,乙,丑,丙,子
34,35,Phil Knight,$40 Billion,24-Feb-38,84.0,United States of America,2038-02-24,"[戊, 午, 甲, 寅, 壬, 申, 庚, 子]",戊,午,甲,寅,壬,申,庚,子
35,36,Vladimir Potanin,$35 Billion,3-Jan-61,61.0,Russia,2061-01-03,"[庚, 辰, 戊, 子, 辛, 巳, 戊, 子]",庚,辰,戊,子,辛,巳,戊,子
36,37,Stephen Schwarzman,$35 Billion,14-Feb-47,75.0,United States of America,2047-02-14,"[丁, 卯, 壬, 寅, 己, 酉, 甲, 子]",丁,卯,壬,寅,己,酉,甲,子
37,38,Jack Ma,$34 Billion,15-Oct-64,57.0,China,2064-10-15,"[甲, 申, 甲, 戌, 壬, 午, 庚, 子]",甲,申,甲,戌,壬,午,庚,子
38,39,Miriam Adelson,$34 Billion,10-Oct-45,76.0,"American, Israeli",2045-10-10,"[乙, 丑, 丙, 戌, 丁, 酉, 庚, 子]",乙,丑,丙,戌,丁,酉,庚,子
39,40,Colin Huang,$33 Billion,1-Jan-80,42.0,China,1980-01-01,"[己, 未, 丙, 子, 癸, 酉, 壬, 子]",己,未,丙,子,癸,酉,壬,子
40,41,Lee Shau Kee,$33 Billion,29-Jan-28,94.0,China,2028-01-29,"[丁, 未, 癸, 丑, 癸, 丑, 壬, 子]",丁,未,癸,丑,癸,丑,壬,子
41,42,Len Blavatnik,$32 Billion,14-Jun-57,65.0,United Kingdom,2057-06-14,"[丁, 丑, 丙, 午, 壬, 寅, 庚, 子]",丁,丑,丙,午,壬,寅,庚,子
42,43,Li Ka-shing,$31 Billion,29-Jul-28,94.0,Canada,2028-07-29,"[戊, 申, 己, 未, 乙, 卯, 丙, 子]",戊,申,己,未,乙,卯,丙,子
43,44,Gina Rinehart,$31 Billion,9-Feb-54,68.0,Australia,2054-02-09,"[甲, 戌, 丙, 寅, 辛, 巳, 戊, 子]",甲,戌,丙,寅,辛,巳,戊,子
44,45,Sheikh Mansour bin Zayed Al Nahyan,$30 Billion,20-Nov-70,51.0,Emirati,2070-11-20,"[庚, 寅, 丁, 亥, 己, 丑, 甲, 子]",庚,寅,丁,亥,己,丑,甲,子
45,46,Masayoshi Son,$30 Billion,11-Aug-57,65.0,Japan,2057-08-11,"[丁, 丑, 戊, 申, 庚, 子, 丙, 子]",丁,丑,戊,申,庚,子,丙,子
46,47,Sultan of Brunei,$30 Billion,15-Jul-46,76.0,Brunei,2046-07-15,"[丙, 寅, 乙, 未, 乙, 亥, 丙, 子]",丙,寅,乙,未,乙,亥,丙,子
47,48,Maha Vajiralongkorn,$30 Billion,28-Jul-52,70.0,Thailand,2052-07-28,"[壬, 申, 丁, 未, 庚, 申, 丙, 子]",壬,申,丁,未,庚,申,丙,子
48,49,Giovanni Ferrero,$28 Billion,21-Sep-64,57.0,Italy,2064-09-21,"[甲, 申, 癸, 酉, 戊, 午, 壬, 子]",甲,申,癸,酉,戊,午,壬,子
49,50,Ken Griffin,$28 Billion,15-Oct-68,53.0,United States of America,2068-10-15,"[戊, 子, 壬, 戌, 癸, 卯, 壬, 子]",戊,子,壬,戌,癸,卯,壬,子
50,51,Abigail Johnson,$28 Billion,19-Dec-61,60.0,United States of America,2061-12-19,"[辛, 巳, 庚, 子, 辛, 未, 戊, 子]",辛,巳,庚,子,辛,未,戊,子
51,52,He Xiangjian,$27 Billion,5-Oct-42,79.0,China,2042-10-05,"[壬, 戌, 己, 酉, 丙, 子, 戊, 子]",壬,戌,己,酉,丙,子,戊,子
52,53,Dieter Schwarz,$27 Billion,24-Sep-39,82.0,Germany,2039-09-24,"[己, 未, 癸, 酉, 己, 酉, 甲, 子]",己,未,癸,酉,己,酉,甲,子
53,54,William Ding,$26 Billion,1-Oct-71,50.0,China,2071-10-01,"[辛, 卯, 丁, 酉, 甲, 辰, 甲, 子]",辛,卯,丁,酉,甲,辰,甲,子
54,55,Shiv Nadar,$25.9 Billion,14-Jul-45,77.0,India,2045-07-14,"[乙, 丑, 癸, 未, 己, 巳, 甲, 子]",乙,丑,癸,未,己,巳,甲,子
55,56,Stefan Persson,$25 Billion,4-Oct-47,74.0,Sweden,2047-10-04,"[丁, 卯, 己, 酉, 辛, 丑, 戊, 子]",丁,卯,己,酉,辛,丑,戊,子
56,57,Joseph Safra,$25 Billion,1-Sep-38,NaN,Brazil,2038-09-01,"[戊, 午, 庚, 申, 辛, 巳, 戊, 子]",戊,午,庚,申,辛,巳,戊,子
57,58,Eric Yuan,$25 Billion,20-Feb-70,52.0,China,2070-02-20,"[庚, 寅, 戊, 寅, 丙, 辰, 戊, 子]",庚,寅,戊,寅,丙,辰,戊,子
58,59,Carl Icahn,$24 Billion,16-Feb-36,86.0,United States of America,2036-02-16,"[丙, 辰, 庚, 寅, 癸, 丑, 壬, 子]",丙,辰,庚,寅,癸,丑,壬,子
59,60,Takemitsu Takizaki,$24 Billion,10-Jun-45,77.0,Japan,2045-06-10,"[乙, 丑, 壬, 午, 乙, 未, 丙, 子]",乙,丑,壬,午,乙,未,丙,子
60,61,Pierre Omidyar,$24 Billion,21-Jun-67,55.0,United States of America,2067-06-21,"[丁, 亥, 丙, 午, 辛, 丑, 戊, 子]",丁,亥,丙,午,辛,丑,戊,子
61,62,Forrest Mars Jr,$23.4 Billion,16-Aug-31,91.0,United States of America,2031-08-16,"[辛, 亥, 丙, 申, 戊, 子, 壬, 子]",辛,亥,丙,申,戊,子,壬,子
62,63,Jorge Paulo Lemann,$23 Billion,26-Aug-39,83.0,Brazil,2039-08-26,"[己, 未, 壬, 申, 庚, 辰, 丙, 子]",己,未,壬,申,庚,辰,丙,子
63,64,Eric Schmidt,$23 Billion,27-Apr-55,67.0,United States of America,2055-04-27,"[乙, 亥, 庚, 辰, 癸, 卯, 壬, 子]",乙,亥,庚,辰,癸,卯,壬,子
64,65,Satoshi Nakamoto,$22 Billion,5-Apr-75,73.0,Japan,1975-04-05,"[乙, 卯, 庚, 辰, 辛, 巳, 戊, 子]",乙,卯,庚,辰,辛,巳,戊,子
65,66,Qin Yinglin,$22 Billion,NaN,57.0,China,NaT,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,67,James Simons,$22 Billion,25-Apr-38,84.0,United States of America,2038-04-25,"[戊, 午, 丙, 辰, 壬, 申, 庚, 子]",戊,午,丙,辰,壬,申,庚,子
67,68,Wang Wei,$22 Billion,NaN,51.0,China,NaT,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,69,James Dyson,$22 Billion,2-May-47,75.0,United Kingdom,2047-05-02,"[丁, 卯, 甲, 辰, 丙, 寅, 戊, 子]",丁,卯,甲,辰,丙,寅,戊,子
69,70,Aliko Dangote,$21 Billion,10-Apr-57,65.0,Nigeria,2057-04-10,"[丁, 丑, 甲, 辰, 丁, 酉, 庚, 子]",丁,丑,甲,辰,丁,酉,庚,子
70,71,Leonard Lauder,$21 Billion,19-Mar-33,89.0,United States of America,2033-03-19,"[癸, 丑, 乙, 卯, 己, 巳, 甲, 子]",癸,丑,乙,卯,己,巳,甲,子
71,72,Andrey Melnichenko,$21 Billion,8-Mar-72,50.0,Russia,2072-03-08,"[壬, 辰, 癸, 卯, 癸, 未, 壬, 子]",壬,辰,癸,卯,癸,未,壬,子
72,73,Sir Evelyn De Rothschild,$20 Billion,29-Aug-31,90.0,England,2031-08-29,"[辛, 亥, 丙, 申, 辛, 丑, 戊, 子]",辛,亥,丙,申,辛,丑,戊,子
73,74,Salman bin Abdulaziz Al Saud,$20 Billion,31-Dec-35,86.0,Saudi Arabia,2035-12-31,"[乙, 卯, 戊, 子, 丙, 寅, 戊, 子]",乙,卯,戊,子,丙,寅,戊,子
74,75,Alexey Mordashov,$20 Billion,26-Sep-65,56.0,Russia,2065-09-26,"[乙, 酉, 乙, 酉, 戊, 辰, 壬, 子]",乙,酉,乙,酉,戊,辰,壬,子
75,76,John Menard,$20 Billion,22-Jan-40,82.0,United States of America,2040-01-22,"[己, 未, 丁, 丑, 己, 酉, 甲, 子]",己,未,丁,丑,己,酉,甲,子
76,77,Elaine Marshall,$20 Billion,18-Nov-45,76.0,United States of America,2045-11-18,"[乙, 丑, 丁, 亥, 丙, 子, 戊, 子]",乙,丑,丁,亥,丙,子,戊,子
77,78,Rupert Murdoch,$20 Billion,11-Mar-31,91.0,Australia,2031-03-11,"[辛, 亥, 辛, 卯, 庚, 戌, 丙, 子]",辛,亥,辛,卯,庚,戌,丙,子
78,79,Dan Gilbert,$20 Billion,17-Jan-62,60.0,United States of America,2062-01-17,"[辛, 巳, 辛, 丑, 庚, 子, 丙, 子]",辛,巳,辛,丑,庚,子,丙,子
79,80,Leonid Mikhelson,$20 Billion,11-Aug-55,67.0,Russia,2055-08-11,"[乙, 亥, 甲, 申, 己, 丑, 甲, 子]",乙,亥,甲,申,己,丑,甲,子
80,81,Pallonji Mistry,$19 Billion,1-Jun-29,NaN,India,2029-06-01,"[己, 酉, 己, 巳, 壬, 戌, 庚, 子]",己,酉,己,巳,壬,戌,庚,子
81,82,Susanne Klatten,$19 Billion,28-Apr-62,60.0,Germany,2062-04-28,"[壬, 午, 甲, 辰, 辛, 巳, 戊, 子]",壬,午,甲,辰,辛,巳,戊,子
82,83,Eduardo Saverin,$19 Billion,19-Mar-82,40.0,Brazil,1982-03-19,"[壬, 戌, 癸, 卯, 辛, 丑, 戊, 子]",壬,戌,癸,卯,辛,丑,戊,子
83,84,Vladimir Lisin,$19 Billion,7-May-56,66.0,Russia,2056-05-07,"[丙, 子, 癸, 巳, 己, 未, 甲, 子]",丙,子,癸,巳,己,未,甲,子
84,85,James Ratcliffe,$19 Billion,18-Oct-52,69.0,United Kingdom,2052-10-18,"[壬, 申, 庚, 戌, 壬, 午, 庚, 子]",壬,申,庚,戌,壬,午,庚,子
85,86,Laurene Powell Jobs,$19 Billion,6-Nov-63,58.0,United States of America,2063-11-06,"[癸, 未, 壬, 戌, 戊, 戌, 壬, 子]",癸,未,壬,戌,戊,戌,壬,子
86,87,Lakshmi Mittal,$18 Billion,2-Sep-50,71.0,India,2050-09-02,"[庚, 午, 甲, 申, 乙, 酉, 丙, 子]",庚,午,甲,申,乙,酉,丙,子
87,88,David & Simon Reuben,$18 Billion,NaN,NaN,United Kingdom,NaT,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,89,Sheikh Khalifa Bin Zayed Al Nahyan,$18 Billion,25-Jan-48,74.0,United Arab Emirates,2048-01-25,"[丁, 卯, 癸, 丑, 甲, 午, 甲, 子]",丁,卯,癸,丑,甲,午,甲,子
89,90,Alisher Usmanov,$18 Billion,9-Sep-53,68.0,Russia,2053-09-09,"[癸, 酉, 辛, 酉, 戊, 申, 壬, 子]",癸,酉,辛,酉,戊,申,壬,子
90,91,Lukas Walton,$18 Billion,NaN,36.0,United States of America,NaT,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,92,Serge Dassault,$17.3 Billion,4-Apr-25,97.0,France,2025-04-04,"[乙, 巳, 庚, 辰, 癸, 卯, 壬, 子]",乙,巳,庚,辰,癸,卯,壬,子
92,93,Pavel Durov,$17 Billion,10-Oct-84,37.0,Russia,1984-10-10,"[甲, 子, 甲, 戌, 丁, 丑, 庚, 子]",甲,子,甲,戌,丁,丑,庚,子
93,94,Donald Bren,$17 Billion,11-May-32,90.0,United States of America,2032-05-11,"[壬, 子, 乙, 巳, 丁, 巳, 庚, 子]",壬,子,乙,巳,丁,巳,庚,子
94,95,Thomas Peterffy,$17 Billion,30-Sep-44,77.0,United States of America,2044-09-30,"[甲, 子, 癸, 酉, 壬, 午, 庚, 子]",甲,子,癸,酉,壬,午,庚,子
95,96,Prince Al Waleed Bin Talal Alsaud,$17 Billion,7-Mar-55,67.0,Saudi Arabia,2055-03-07,"[乙, 亥, 己, 卯, 壬, 子, 庚, 子]",乙,亥,己,卯,壬,子,庚,子
96,97,Harold Hamm,$17 Billion,11-Dec-45,76.0,United States of America,2045-12-11,"[乙, 丑, 戊, 子, 己, 亥, 甲, 子]",乙,丑,戊,子,己,亥,甲,子
97,98,Viktor Vekselberg,$17 Billion,14-Apr-57,65.0,Russia,2057-04-14,"[丁, 丑, 甲, 辰, 辛, 丑, 戊, 子]",丁,丑,甲,辰,辛,丑,戊,子
98,99,Steven Cohen,$16 Billion,11-Jun-56,66.0,United States of America,2056-06-11,"[丙, 子, 甲, 午, 甲, 午, 甲, 子]",丙,子,甲,午,甲,午,甲,子
99,100,Stefan Quandt,$16 Billion,9-May-66,56.0,Germany,2066-05-09,"[丙, 戌, 癸, 巳, 癸, 丑, 壬, 子]",丙,戌,癸,巳,癸,丑,壬,子

In [ ]:
#export to csv
rich.to_csv('C:\\Users\\TOSHIBA\\Documents\\Github\\FateAi\\DATAS\\top_100_richest_bazi.csv', index=False)

In [8]:
import numpy as np

rich[['man年干', 'man年支', 'man月干', 'man月支', 'man日干', 'man日支', 'man時干', 'man時支']] = rich['bazi_man'].apply(lambda x: [x[0], x[1], x[2], x[3], x[4], x[5], x[6], x[7]] if x is not None else [np.nan]*8).apply(pd.Series)

In [11]:
def printBazi(df):
    for index, row in df.iterrows():
        print(f"{row['man日干']}{row['man月干']}{row['man年干']}|")
        print(f"{row['man日支']}{row['man月支']}{row['man年支']}|")
        collist = [col for col in row.index if row[col] and df[col].dtype == 'bool']
        print(collist)
        print()

In [12]:
printBazi(rich)

己甲辛|
巳午卯|
[]

乙乙癸|
巳丑未|
[]

戊丙壬|
寅午午|
[]

己丁己|
卯卯巳|
[]

丁丙乙|
未戌亥|
[]

丁甲庚|
酉申戌|
[]

辛乙癸|
酉卯丑|
[]

己庚癸|
丑申丑|
[]

乙辛丙|
亥卯子|
[]

戊壬甲|
戌申子|
[]

nannannan|
nannannan|
[]

丙甲丁|
午辰丑|
[]

乙丁己|
卯丑未|
[]

辛庚壬|
未戌申|
[]

丁己癸|
未未酉|
[]

甲辛丙|
午卯辰|
[]

癸壬壬|
未寅戌|
[]

戊己甲|
申巳子|
[]

庚甲甲|
戌戌子|
[]

戊戊戊|
申午辰|
[]

nannannan|
nannannan|
[]

乙癸己|
卯酉巳|
[]

乙甲壬|
丑辰午|
[]

丙丙乙|
寅戌卯|
[]

癸戊乙|
巳寅酉|
[]

庚丙丙|
申申辰|
[]

庚丙丁|
子午丑|
[]

壬戊辛|
申戌卯|
[]

辛辛戊|
丑酉辰|
[]

壬壬辛|
申辰未|
[]

己乙癸|
未卯亥|
[]

癸丙己|
丑寅巳|
[]

己丙乙|
酉戌卯|
[]

乙甲己|
丑戌未|
[]

壬甲戊|
申寅午|
[]

辛戊庚|
巳子辰|
[]

己壬丁|
酉寅卯|
[]

壬甲甲|
午戌申|
[]

丁丙乙|
酉戌丑|
[]

癸丙己|
酉子未|
[]

癸癸丁|
丑丑未|
[]

壬丙丁|
寅午丑|
[]

乙己戊|
卯未申|
[]

辛丙甲|
巳寅戌|
[]

己丁庚|
丑亥寅|
[]

庚戊丁|
子申丑|
[]

乙乙丙|
亥未寅|
[]

庚丁壬|
申未申|
[]

戊癸甲|
午酉申|
[]

癸壬戊|
卯戌子|
[]

辛庚辛|
未子巳|
[]

丙己壬|
子酉戌|
[]

己癸己|
酉酉未|
[]

甲丁辛|
辰酉卯|
[]

己癸乙|
巳未丑|
[]

辛己丁|
丑酉卯|
[]

辛庚戊|
巳申午|
[]

丙戊庚|
辰寅寅|
[]

癸庚丙|
丑寅辰|
[]

乙壬乙|
未午丑|
[]

辛丙丁|
丑午亥|
[]

戊丙辛|
子申亥|
[]

庚壬己|
辰申未|
[]

癸庚乙|
卯辰亥|
[]

辛庚乙|
巳辰卯|
[]

nannannan|
nannannan|
[]

壬丙戊|
申辰午|
[]

nannannan|
nannannan|
[]

丙甲丁|
寅辰卯|
[]

丁甲丁|
酉辰丑|
[]

己乙癸|
巳卯丑|
[]

癸癸壬|
未卯辰|
[]

辛丙辛|
丑申亥|
[]

丙戊乙|
寅子卯|
[]

戊乙乙|
辰酉酉|
[]

己丁己|
酉丑未|
[]

丙丁乙|
子亥丑|
[]

庚辛辛|
戌卯亥|
[]

庚辛辛|
子丑巳|
[]

己甲乙|
丑申亥|
[]

壬己己|
戌巳酉|
[]

辛甲壬|
巳辰午|
[]

辛癸壬|
丑卯戌|
[]

己癸丙|
未巳子|
[]

壬庚壬|
午戌申|
[]

戊壬癸|
戌戌未|
[]

乙甲庚|
酉申午|
[]

nannannan|
nannannan|
[]

甲癸丁|
午丑卯|
[]

戊辛癸|
申酉酉|
[]

nannannan|
nannannan|
[]

癸庚乙|
卯辰巳|
[]

丁甲甲|
丑戌子|
[]

丁乙壬|
巳巳子|
[]

壬癸甲|
午酉子|
[]

壬己乙|
子卯亥|
[]

己戊乙|
亥子丑|
[]

辛甲丁|
丑辰丑|
[]

甲甲丙|
午午子|
[]

癸癸丙|
丑巳戌|
[]