In [3]:
import sys
sys.path.append(r"C:\Users\Atlas\Documents\GitHub\FateAi\CrystalMarch\bazi")
# import main
import metaphysic

ModuleNotFoundError: No module named 'metaphysic'

In [2]:
ba=metaphysic.bazi(1996,9,17,3)
ba=ba.split("-")
bazi=[]
for i in ba:
    # print(i.split())
    bazi.append(i[0])
    bazi.append(i[1])
bazi

changed sth
输入:[1996-9-17]; 输出:[1996-8-5]; 天干地支:[丙子-丁酉-丁巳]; 生肖:[鼠]

['丙', '子', '丁', '酉', '丁', '巳', '壬', '寅']

In [4]:
# make a df with the following cols: 年干 年支 月干 月支 日干 日支 时干 时支 only
import pandas as pd
# df = pd.DataFrame(data,columns=['Name','Gender',"BirthyYear","Bmonth","Bday","FatherDeadY"])

bazidf=pd.DataFrame(columns=["年干","年支","月干","月支","日干","日支","时干","时支"])
# bazidf.columns=["年干","年支","月干","月支","日干","日支","时干","时支"]

In [5]:
bazidf

Empty DataFrame
Columns: [年干, 年支, 月干, 月支, 日干, 日支, 时干, 时支]
Index: []

In [6]:
# add bazi to bazidf
bazidf.loc[0]=bazi
bazidf

  年干 年支 月干 月支 日干 日支 时干 时支
0  丙  子  丁  酉  丁  巳  壬  寅