In [1]:
import sys
sys.path.append(r"C:\Users\TOSHIBA\Documents\Github\FateAi\crystal-bazi")
# import main
import metaphysic

In [2]:
def getBazi(year,month,day,hour):
    ba=metaphysic.bazi(1996,9,17,3)
    ba=ba.split("-")
    bazi=[]
    for i in ba:
        # print(i.split())
        bazi.append(i[0])
        bazi.append(i[1])
    return bazi

In [3]:
bazi=getBazi(1996,9,17,3)
bazi

changed sth
输入:[1996-9-17]; 输出:[1996-8-5]; 天干地支:[丙子-丁酉-丁巳]; 生肖:[鼠]

['丙', '子', '丁', '酉', '丁', '巳', '壬', '寅']

In [4]:
# make a df with the following cols: 年干 年支 月干 月支 日干 日支 时干 时支 only
import pandas as pd
# df = pd.DataFrame(data,columns=['Name','Gender',"BirthyYear","Bmonth","Bday","FatherDeadY"])

bazidf=pd.DataFrame(columns=["年干","年支","月干","月支","日干","日支","时干","时支"])
# bazidf.columns=["年干","年支","月干","月支","日干","日支","时干","时支"]

In [5]:
bazidf

Empty DataFrame
Columns: [年干, 年支, 月干, 月支, 日干, 日支, 时干, 时支]
Index: []

In [6]:
# add bazi to bazidf
bazidf.loc[0]=bazi
bazidf

  年干 年支 月干 月支 日干 日支 时干 时支
0  丙  子  丁  酉  丁  巳  壬  寅

In [2]:
def solution(inputString):
    p1=0
    p2=len(inputString)-1
    
    while(p1!=p2):
        if inputString[p1]!=inputString[p2]:
            return False
        p1=p1+1
        p2=p2-1
    return True
solution('hlbeeykoqqqqokyeeblh')

IndexError: string index out of range

In [3]:
def solution(a, b, k):
    p1=0
    p2=len(b)-1
    t=0
    while(p1<=p2):
        c=str(a[p1])+str(b[p2])
        if int(c)<k:
            t=t+1
    
    return t
a = [1, 2, 3]
b = [1, 2, 3]
k = 31
solution(a, b, k)

KeyboardInterrupt: